"""Empagliflozin-HFpEF review: EMPERIAL (one paper, two trials) and EMPA-VISION (two separately randomised cohorts).
Declarations: docs/multi_trial_reports.json, docs/comparison_families.json (generated by
outputs/handover/empagliflozin_sources/make_empagliflozin_fixtures.py, every span asserted against held bytes)."""
import copy
import json
import os
import shutil

import pytest

from harness import comparison_family as cf, fetch, multi_trial_report as mtr, pipeline, result_status as rs

ROOT = pipeline.ROOT
SLUG = "empagliflozin-hfpef-hosp"
CONFIG = json.load(open(os.path.join(ROOT, "topics", SLUG + ".json"), encoding="utf-8"))
COMPOSITE = "Composite cardiovascular death or worsening heart failure"
_REV = {}


def _review():
    if "rv" not in _REV:
        _REV["rv"] = pipeline.build_review_core(SLUG, CONFIG, fetch.ensure(CONFIG, ""), "test")
    return _REV["rv"]


def _emperial(root=ROOT):
    return next(r for r in mtr.resolve(root, CONFIG) if r["report_id"] == "PMID 33351892")


def test_emperial_links_both_trials_and_only_preserved_is_relevant():
    r = _emperial()
    t = {x["label"]: x for x in r["trials"]}
    assert t["EMPERIAL-Preserved"]["registration"] == "NCT03448406" and t["EMPERIAL-Preserved"]["relevant"]
    assert t["EMPERIAL-Reduced"]["registration"] == "NCT03448419" and not t["EMPERIAL-Reduced"]["relevant"]
    assert (t["EMPERIAL-Preserved"]["n_randomised"], t["EMPERIAL-Reduced"]["n_randomised"]) == (315, 312)


def test_emperial_preserved_row_is_linked_and_no_longer_source_not_retrieved():
    o = next(o for o in _review()["outcomes"] if o["name"] == COMPOSITE)
    row = next(a for a in o["declared_absent_trials"] if "NCT03448406" in str(a["id"]))
    assert row["multi_trial_report"]["shared_with"] == ["NCT03448419"]
    st = row["result_status"]
    assert st["state"] == rs.RETRIEVED_NOT_REPORTED and "REGISTRY_RESULTS" in st["coverage"]
    assert st["supersedes"]["state"] == rs.NOT_YET_RETRIEVED     # the replaced state is kept, not erased


def test_preserved_exploratory_harms_serious_bound_the_rest_unresolved():
    pres = next(t for t in _emperial()["trials"] if t["label"] == "EMPERIAL-Preserved")
    rows = {x["outcome"]: x for x in pres["registry_results"]["exploratory_harms"]["rows"]}
    assert rows["Serious adverse events"]["values"] == {"ai": 20, "n1i": 157, "ci": 29, "n2i": 158}
    assert rows["Any adverse event"]["state"] == rows["Adverse event leading to discontinuation"]["state"] == "REPORTED_UNRESOLVED"
    assert "values" not in rows["Any adverse event"]      # relayed numbers are not held bytes: never data
    assert "EXPLORATORY" in pres["registry_results"]["exploratory_harms"]["_policy"]


def test_a_corrupted_exploratory_witness_fails_closed(tmp_path):
    # PLANT: the serious-event span edited 29 -> 28; the resolver must refuse, not render it
    for d in ("docs",):
        (tmp_path / d).mkdir()
    m = json.load(open(os.path.join(ROOT, "docs", "multi_trial_reports.json"), encoding="utf-8"))
    rep = next(r for r in m["reports"] if r["report_id"] == "PMID 33351892")
    w = rep["trials"][0]["registry_results"]["exploratory_harms"]["rows"][0]["witnesses"][1]
    w["span"] = w["span"].replace('"seriousNumAffected":29', '"seriousNumAffected":28')
    m["reports"] = [rep]
    (tmp_path / "docs" / "multi_trial_reports.json").write_text(json.dumps(m), encoding="utf-8")
    shutil.copytree(os.path.join(ROOT, "evidence", "acquisition_cascade", "held", "NCT03448406"),
                    tmp_path / "evidence" / "acquisition_cascade" / "held" / "NCT03448406")
    for sub in ("EMPERIAL", "EMPERIAL-Reduced"):
        shutil.copytree(os.path.join(ROOT, "evidence", "acquisition_cascade", "held", sub),
                        tmp_path / "evidence" / "acquisition_cascade" / "held" / sub)
    with pytest.raises(ValueError, match="span not in the held bytes"):
        mtr.resolve(str(tmp_path), CONFIG)


def test_a_pooled_row_from_emperial_reduced_is_a_blocking_problem():
    # PLANT: the HFrEF trial pooled into this HFpEF review
    rv = copy.deepcopy(_review())
    o = next(o for o in rv["outcomes"] if o["name"] == COMPOSITE)
    o["trials"] = [{"id": "NCT03448419", "ai": 1, "n1i": 156, "ci": 1, "n2i": 156}]
    rv["multi_trial_reports"] = [_emperial()]
    assert [p["kind"] for p in mtr.problems(rv)] == ["COMBINED_POPULATION_IMPORTED"]


# ------------------------------------------------------------------------------------------ EMPA-VISION cohorts
EV_REC = {"id": "NCT03332212", "id_type": "nct", "acronym": "EMPA-VISION",
          "title": "EMPA-VISION: A Randomised, Double-blind, Placebo-controlled, Mechanistic Cardiac Magnetic Resonance Study",
          "conditions": ["Heart Failure With Reduced Ejection Fraction", "Heart Failure With Preserved Ejection Fraction"]}


def test_the_hfref_cohort_does_not_exclude_the_hfpef_cohort():
    got = cf.screen_registration(EV_REC, CONFIG)
    comps = {c["comparison_id"]: c for c in got["comparisons"]}
    assert comps["EMPA-VISION:HFpEF-cohort"]["eligibility"] == cf.ELIGIBLE
    assert comps["EMPA-VISION:HFrEF-cohort"]["eligibility"] == cf.INELIGIBLE
    assert got["decision"] == "include"
    assert comps["EMPA-VISION:HFpEF-cohort"]["arms"] == {"empagliflozin": 18, "placebo": 18}
    assert comps["EMPA-VISION:HFpEF-cohort"]["result_state"] == "PUBLISHED_NO_TARGET_OUTCOME"


def test_the_72_are_never_imported_as_hfpef():
    # PLANT: a whole-trial row (35 vs 37) with no comparison named -> held out, never pooled
    keep, held = cf.hold_whole_trial(SLUG, COMPOSITE, [{"id": "NCT03332212", "ai": 1, "n1i": 35, "ci": 1, "n2i": 37}])
    assert keep == [] and held[0]["reason_code"] == "WHOLE_TRIAL_ACROSS_COMPARISONS"
    keep, held = cf.hold_whole_trial(SLUG, COMPOSITE, [{"id": "NCT03332212", "comparison_id": "EMPA-VISION:HFpEF-cohort",
                                                       "ai": 1, "n1i": 18, "ci": 1, "n2i": 18}])
    assert held == [] and len(keep) == 1
    fam = next(f for f in cf.load(ROOT) if f["family_id"] == "NCT03332212")
    assert fam["whole_trial"]["n"] == 72 and fam["whole_trial"]["policy"] == "NEVER_IMPORTED_AS_EITHER_COHORT"


def test_empa_vision_known_missing_entry_names_its_cohorts_and_held_source():
    k = json.load(open(os.path.join(ROOT, "docs", "known_eligible_missing.json"), encoding="utf-8"))["topics"][SLUG]
    e = next(x for x in k if x["trial"] == "EMPA-VISION")
    assert e["status"] == "source_held_cohorts_declared" and e["registration"] == "NCT03332212"
    assert os.path.exists(os.path.join(ROOT, e["acquisition"]["held_path"]))
