"""All served harm panels: offline browser contract for the HRM suppression rule."""
import json
import os
from pathlib import Path

import pytest

pytest.importorskip("playwright")
from playwright.sync_api import sync_playwright
from harness import harms


def test_hrm_all_served_harm_panels():
    root = Path(__file__).resolve().parents[1]
    candidates = [Path(os.environ.get("PROGRAMFILES(X86)", "")) / "Microsoft/Edge/Application/msedge.exe",
                  Path(os.environ.get("PROGRAMFILES", "")) / "Google/Chrome/Application/chrome.exe"]
    exe = next((p for p in candidates if p.is_file()), None)
    assert exe, "Local browser required; downloads forbidden"
    # Serve actual generated bytes through the browser route. A shared machine's
    # existing port-8000 server must not substitute another checkout's pages.
    def serve(route):
        prefix = "http://127.0.0.1:8000/"
        url = route.request.url
        if not url.startswith(prefix):
            route.abort()
            return
        path = (root / url[len(prefix):]).resolve()
        if not path.is_relative_to(root) or not path.is_file():
            route.abort()
            return
        route.fulfill(status=200, content_type="text/html; charset=utf-8", body=path.read_bytes())

    with sync_playwright() as p:
        browser = p.chromium.launch(executable_path=str(exe), headless=True)
        try:
            page = browser.new_page()
            page.route("**/*", serve)
            errors = []
            page.on("pageerror", lambda error: errors.append(str(error)))
            paths = sorted((root / "docs/reviews").glob("*/review.json"))
            assert len(paths) == 32
            for path in paths:
                review = json.loads(path.read_text(encoding="utf-8"))
                assert page.goto(f"http://127.0.0.1:8000/docs/reviews/{path.parent.name}/index.html").status == 200
                page.locator('button[data-t="harms"]').click()
                panel = page.locator("#tab-harms")
                assert panel.is_visible()
                incomplete = [o for o in review["outcomes"] if harms.synthesis_incomplete(o)]
                assert panel.locator(".harms-synthesis-gated").count() == len(incomplete)
                for outcome in incomplete:
                    block = panel.evaluate("""(panel, name) => {
                        const heading = [...panel.querySelectorAll('h4')].find(e => e.textContent === name);
                        const box = document.createElement('div');
                        for (let node = heading.nextElementSibling; node && node.tagName !== 'H4'; node = node.nextElementSibling)
                            box.append(node.cloneNode(true));
                        return {ledger: box.querySelectorAll('.harms-debt-ledger').length,
                                quantitative: box.querySelectorAll('table.kv').length, text: box.textContent};
                    }""", outcome["name"])
                    assert block["ledger"] == 1 and block["quantitative"] == 0
                    assert harms.INCOMPLETE_MESSAGE in block["text"]
                    for item in harms.reporting_ledger(outcome):
                        assert str(item.get("label") or item["id"]) in block["text"]
                assert "estimator PUBLISHED_UNADJUSTED;" not in page.content()
                assert "estimator PUBLISHED_ADJUSTED;" not in page.content()
            assert not errors, errors
        finally:
            browser.close()
