"""Served-artefact leak scanner (audit 25/26): suppression applied at the page renderer does NOT reach the
DERIVED artefacts (docs/*.json aggregates), and those artefacts are ALSO served (a reader can open the JSON,
and pages embed it). A suppressed pool that still publishes its estimate / CI / tau^2 / prediction interval /
significance through an aggregate snapshot is the same leak, one layer down. This is a GENERAL leak detector:
it maps every topic to its suppressed/refused STATES, then scans every served aggregate artefact for a derived
statistic attributed to a topic in a state that forbids it.

'Suppression lives at the source' means the per-review result object already has its pooled numbers popped
(pipeline), so review.json is clean by construction and reproduced by the gate. The remaining surface is the
aggregate docs/*.json, which are generated by separate scripts and can go stale or recompute — exactly where
the iv-iron tau^2=0.178 leak was found. This scanner is the durable guard over that surface.
"""
from __future__ import annotations

import glob
import json
import os

from harness.target import TargetUnresolvable, describe_target, refusal as target_refusal

# Derived pooled statistics that must NOT be published for a topic whose primary pool is suppressed/refused.
_DERIVED_KEYS = {
    "estimate", "ci_low", "ci_high", "tau2", "i2",
    "estimate_fixed", "ci_low_fixed", "ci_high_fixed",
    "pi_low", "pi_high", "ci_crosses_null",
}


def suppressed_states(docs_dir: str) -> dict:
    """Map slug -> set of states that forbid publishing a derived pooled statistic for it."""
    out: dict[str, set] = {}
    for f in glob.glob(os.path.join(docs_dir, "reviews", "*", "review.json")):
        slug = os.path.basename(os.path.dirname(f))
        try:
            r = json.load(open(f, encoding="utf-8"))
        except (OSError, ValueError):
            continue
        prim = next((o for o in r.get("outcomes", []) if o.get("primary")), None)
        res = (prim or {}).get("result") or {}
        states = set()
        if res.get("suppressed_incompatible"):
            states.add("estimand_incompatible")
        g = r.get("grade") or {}
        if g.get("certainty") == "not_rateable" or g.get("not_rateable_reason"):
            states.add("grade_not_rateable")
        if states:
            out[slug] = states
    return out


def _strand_permitted_ids(data) -> set:
    """Object ids of derived stats PERMITTED for a suppressed-because-incompatible topic.

    A topic is suppressed when its estimands are INCOMPATIBLE -- the forbidden object is the
    COMBINED/primary pool. A DECLARED strand pool that stays inside one compatibility class is not
    that pool; it is the honest decomposition, and publishing it (clearly labelled, alongside the
    suppression reason and the refused cross-strand counterfactual) is disclosure, not a leak.

    This carve-out is TIGHT and fail-closed. It activates only for an artefact that carries the full
    honest-disclosure structure -- a `strands` list, `why_topic_is_suppressed`, and
    `refused_cross_endpoint_pool` -- and it permits derived stats ONLY inside a strand that is
    compatibility-HOMOGENEOUS: every member declares the SAME (event_process, endpoint) as the strand.
    A strand that mixes event_process or endpoint (a disguised combined pool) is NOT permitted, so its
    pool still leaks; and any derived stat attributed to the slug OUTSIDE the strands structure is NOT
    permitted (the historical iv-iron tau^2 leak still fires)."""
    permitted = set()
    if not (isinstance(data, dict) and isinstance(data.get("strands"), list)
            and data.get("why_topic_is_suppressed") and data.get("refused_cross_endpoint_pool")):
        return permitted
    for strand in data["strands"]:
        if not isinstance(strand, dict):
            continue
        ep, endp = strand.get("event_process"), strand.get("endpoint")
        members = strand.get("members")
        if not (ep and endp and isinstance(members, list) and members):
            continue  # malformed -> not permitted (fail closed)
        homogeneous = all(isinstance(m, dict)
                          and m.get("event_process") == ep and m.get("endpoint") == endp
                          for m in members)
        if homogeneous:
            permitted.add(id(strand))  # whole strand subtree (members + pool) is permitted
    return permitted


def _derived_here(obj, permitted: set | None = None) -> list:
    """Derived-stat keys carrying a real (non-null) value anywhere in this object's subtree, EXCEPT
    inside a subtree whose object id is in `permitted` (a validated homogeneous strand)."""
    permitted = permitted or set()
    found = []

    def walk(o, path=""):
        if id(o) in permitted:
            return  # permitted strand subtree -- its pooled stats are legitimate disclosure
        if isinstance(o, dict):
            for k, v in o.items():
                if k in _DERIVED_KEYS and v is not None and not (k == "ci_crosses_null" and v is False):
                    if isinstance(v, (int, float)) or v is True:
                        found.append(f"{path}{k}={v}")
                walk(v, f"{path}{k}.")
        elif isinstance(o, list):
            for i, v in enumerate(o):
                walk(v, f"{path}{i}.")

    walk(obj)
    return found


def _attributed_objects(data, supp: set):
    """Yield (slug, object) for every sub-object attributable to a suppressed slug: either a dict keyed by
    the slug, or a dict carrying a 'slug'/'topic' field equal to a suppressed slug."""
    def walk(o):
        if isinstance(o, dict):
            tag = o.get("slug") or o.get("topic")
            if tag in supp:
                yield tag, o
            for k, v in o.items():
                if k in supp and isinstance(v, (dict, list)):
                    yield k, v
                yield from walk(v)
        elif isinstance(o, list):
            for v in o:
                yield from walk(v)
    yield from walk(data)


def scan(docs_dir: str) -> list:
    """Scan every served aggregate artefact (docs/*.json) for a derived pooled statistic attributed to a
    topic in a suppressed state. Returns a list of leak dicts."""
    supp = suppressed_states(docs_dir)
    leaks = []
    for f in sorted(glob.glob(os.path.join(docs_dir, "*.json"))):
        try:
            data = json.load(open(f, encoding="utf-8"))
        except (OSError, ValueError):
            continue
        permitted = _strand_permitted_ids(data)
        seen = set()
        for slug, obj in _attributed_objects(data, set(supp)):
            found = _derived_here(obj, permitted)
            for fnd in found:
                key = (os.path.basename(f), slug, fnd)
                if key in seen:
                    continue
                seen.add(key)
                leaks.append({"artefact": os.path.basename(f), "slug": slug,
                              "states": sorted(supp[slug]), "leak": fnd})
    return leaks


def describe_scan_target(docs_dir: str, root: str | None = None) -> str:
    root = os.path.abspath(root or os.getcwd())
    docs_abs = os.path.abspath(docs_dir)
    paths = []
    for pattern in (os.path.join(docs_abs, "*.json"), os.path.join(docs_abs, "reviews", "*", "review.json")):
        for path in sorted(glob.glob(pattern)):
            paths.append(os.path.relpath(path, root).replace(os.sep, "/"))
    try:
        return describe_target(root, paths=paths, label="leakscan")
    except TargetUnresolvable as exc:
        return target_refusal("leakscan", str(exc))


def main(argv):
    docs = argv[0] if argv else "docs"
    target_line = describe_scan_target(docs)
    print(target_line)
    if target_line.startswith("TARGET leakscan: COULD-NOT-EXECUTE"):
        return 1
    supp = suppressed_states(docs)
    leaks = scan(docs)
    print(f"suppressed-state topics: {len(supp)} ({', '.join(sorted(supp))})")
    by_state = {}
    for lk in leaks:
        for s in lk["states"]:
            by_state.setdefault(s, 0)
            by_state[s] += 1
    if not leaks:
        print("LEAK SCAN CLEAN: no derived pooled statistic is published for any suppressed-state topic.")
        return 0
    print(f"LEAK SCAN FOUND {len(leaks)} leak(s):")
    for lk in leaks:
        print(f"  - {lk['artefact']}: {lk['slug']} [{','.join(lk['states'])}] -> {lk['leak']}")
    print("by state:", by_state)
    return 1


if __name__ == "__main__":
    import sys
    sys.exit(main(sys.argv[1:]))
