"""Located regex defects: plant id -> why the CURRENT pattern fails it. Each runs as a strict xfail in
tests/test_regex_plants.py, so a fix flips it to a pass (and must remove the entry) and a regression cannot hide."""

# plant id -> why the current pattern fails it (a located defect, not a wish)
KNOWN_DEFECTS: dict[str, str] = {
    'rob2.py:search:b4e124d7bc-accept-3':
        "RX-OL1 (found 2026-09-24 by this plant): 'montgomery[- ]?a?sberg' needs an ASCII 'a' and a hyphen/space, so the scale's own spelling 'Montgomery–Åsberg' (en dash, Å) is not read as MADRS unless the text also says 'MADRS'. Latent: all 11 held D5 texts naming the scale spell it 'Asberg' and carry '(MADRS)'. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:74ee9684cf-accept-2':
        "RX-OL2 (found 2026-09-24 by this plant): only the word 'recurrent' marks a recurrence, so 'VTE recurrence' / 'recurrence of VTE' never yields RECURRENT_VTE. Latent: 0 held D5 texts use that phrasing. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:2ee9bddbd6-accept-3':
        "RX-OL3 (found 2026-09-24 by this plant): 'deep vein thrombosis' is listed but 'deep venous thrombosis' is not, so that spelling (with no VTE/DVT abbreviation) is not read as a VTE event. Latent: 0 held D5 texts. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:2302517c9d-accept-2':
        "RX-OL4 (found 2026-09-24 by this plant): only 'all-cause mortality' is read, so 'all-cause death' / 'death from any cause' yield no ALL_CAUSE_MORTALITY component. Reachable: held D5 inputs of dpp4-mace-t2d 28893244 ('Number of Participants With an Event of All-Cause Death'; 'All-cause death was death from any cause') and doac-vte-recurrence 23808982; the recorded D5 levels are 'low', effect on a verdict not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:2302517c9d-accept-3':
        "RX-OL4 (found 2026-09-24 by this plant): 'death from any cause' is not read as all-cause mortality (see accept-2). Reachable in held dpp4-mace-t2d 28893244 D5 description. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:052d9d5ea5-accept-4':
        "RX-OL5 (found 2026-09-24 by this plant): CV death is read only as 'cv death' / 'cardiovascular [(..)] death' / 'death from cardiovascular causes', so 'CV-related death' is missed. Reachable and consequential in held text: dpp4-mace-t2d 28893244's registered MACE measure '(Confirmed CV-Related Death, Fatal and Nonfatal MI, and Fatal and Nonfatal Stroke)' reads as {NONFATAL_MI, NONFATAL_STROKE} -- no CV death, so not 3-point MACE; the recorded D5 basis cites a secondary-outcome match instead, and whether this defect is why is not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:052d9d5ea5-accept-5':
        "RX-OL5 (found 2026-09-24 by this plant): 'death due to cardiovascular causes' (and held 'Death Due to CV Cause', noac-vs-warfarin-af-stroke 24251359) is not read as CV death (see accept-4). The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:052d9d5ea5-refuse-2':
        "RX-OL6 (found 2026-09-24 by this plant): '\\bcardiovascular' fires after the hyphen in 'non-cardiovascular death', so non-CV death adds a CV_DEATH component (the defect target_endpoint masks and RX-TE2 names for 'vascular'). Reachable: held D5 description of omega3-cardiovascular-events 33190147 reads as ['CV_DEATH'] through this phrase; recorded D5 level 'low', effect on a verdict not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:4494298990-accept-4':
        "RX-OL7 (found 2026-09-24 by this plant): 'hospitali[sz](?:ation|ed)\\b' has no plural, so 'hospitalisations for heart failure' / 'heart failure hospitalizations' yield no HF_HOSPITALISATION component. Reachable: the held registered measure of iv-iron-hfref-hosp 40159390 ('Rate of total (first and recurrent) events of hospitalisations for heart failure (HF)') reads as an empty component set; recorded D5 level 'low' (matched on another registered outcome), effect not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'rob2.py:search:a26bd545ce-accept-3':
        "RX-OL8 (found 2026-09-24 by this plant): 'major adverse cardiac events' (a common expansion of MACE) is not a MACE term. Latent: all 5 held D5 texts using it also carry '(MACE)'. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:_INDUSTRY-accept-3':
        "RX-OL9 (found 2026-09-24 by this plant): the group ends in '\\b', and after 'Inc.' a boundary needs a following word character, so 'Inc.' before a space / end never marks industry. Reachable and consequential: with 'Inc.' matched, funding.detect() changes from no class to industry on 2 held documents (sglt2-primary-prevention-hf records.json#27025436 'FUNDING: Corvia Medical Inc.'; probiotics-aad-prevention ft_22371721 'BIO K+ International Inc.'), measured 2026-09-24 with a scratch-patched pattern; whether those reach a served funding row is not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:_PUBLIC-accept-3':
        "RX-OL10 (found 2026-09-24 by this plant): the public-funder list has no NHLBI (nor the other NIH institutes by name), so 'funded by the National Heart, Lung, and Blood Institute' alone is not public. Latent: adding it changes funding.detect() on 0 held documents (the NIH is named alongside). The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:_DRUG_SUPPLY-accept-3':
        "RX-OL11 (found 2026-09-24 by this plant): only the passive form ('<drug> was provided by X') is read, so 'X provided the study drug' is not a drug-supply statement. The phrasing is in held full text (semaglutide-obesity-weight ft_41778920, tocilizumab-covid19-mortality ft_33080005); effect not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:_INDUSTRY_AUTHORS-accept-2':
        "RX-OL12 (found 2026-09-24 by this plant): the employer list is 8 companies, so employees of any other company are not industry authors. Reachable: held iv-iron-hfref-hosp ft_25176939 states 'V.L. and B.R. are employees of Vifor Pharma Ltd.' and industry_authors_present is False for it. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:_INDUSTRY_AUTHORS-refuse-1':
        "RX-OL13 (found 2026-09-24 by this plant): '.*?' under re.S lets 'employee of' reach a company named in any later sentence, so a university employee plus 'funded by Pfizer' reads as industry authors. Latent: the 2 held matches longer than 250 chars (glp1-ra-mace-t2d ft_27295427, ft_28910237) are 'employees of the sponsor' where the sponsor is that company, so the verdict happens to be right. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:L84-accept-2':
        "RX-OL14 (found 2026-09-24 by this plant): 'analys(?:ed|is|es)|analyz(?:ed|es|ing)' has no 'analysing', so the British spelling of a funder's analysis role is missed. Latent: 0 served held basis spans use it. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:split:d3389b2de7-refuse-2':
        "RX-OL15 (found 2026-09-24 by this plant): the sponsor split on ',', 'and' and '&' cuts inside one sponsor's name. Reachable and served: 9 held detect() sponsor lists are fragmented, e.g. doac-vte-recurrence records.json#21830957 -> ['Johnson', 'Johnson', 'Bayer']. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:split:d3389b2de7-refuse-3':
        "RX-OL15 (found 2026-09-24 by this plant): 'Bill & Melinda Gates Foundation' is split into 'Bill' / 'Melinda Gates Foundation' (held: tranexamic-acid-pph records.json#39461793, #41519151; iv-iron-hfref-hosp #28919117). The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'funding.py:split:d3389b2de7-refuse-4':
        "RX-OL15 (found 2026-09-24 by this plant): 'National Heart, Lung, and Blood Institute' is split into 3 sponsors (held: colchicine-recurrent-pericarditis records.json#34051877). The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'hand_binding.py:_REF_JUNK-accept-5':
        "RX-OL16 (found 2026-09-24 by this plant): the DOI marker '10\\.\\d{4}/' needs exactly 4 registrant digits, so a 5-digit DOI such as the Crossref funder registry's '10.13039/...' is not debris. Reachable: 5 held full-text prose sentences carry one and are kept in the definition pool (omega3-cardiovascular-events ft_38199870, semaglutide-obesity-weight ft_41778920); effect on a binding not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'hand_binding.py:findall:ea304f7fe8-accept-1':
        "RX-OL17 (found 2026-09-24 by this plant): '<tr>.*?</tr>' needs a bare '<tr>', so a row with attributes (<tr style=...>, <tr content-type=...>) is not a row. Reachable and consequential: table_rows() drops 17 held table-body rows carrying numeric cells (colchicine-secondary-cv-prevention ft_32295417, probiotics-aad-prevention ft_39497860), so no hand binding can locate a result in them. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'hand_binding.py:_RESULT_PAREN-accept-2':
        "RX-OL18 (found 2026-09-24 by this plant): a result parenthesis must say '95%' or 'CI', so the older '95 percent confidence interval' form is not a result and _owning_clause treats the sentence as one clause. Reachable: 12 held abstract sentences (e.g. sacubitril-valsartan-hfref records.json#2057034); effect not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-24.",
    'absence.py:_ESTIMAND_SUFFIX-refuse-1':
        "RX-OL23 (found 2026-09-25 by this plant): under re.I the estimand word 'OR' also matches the conjunction 'or', so _terms strips it out of an outcome keyword: 'CV death or HHF' -> 'cv death hhf', which can never be a substring of a sentence saying 'CV death or HHF'; 'adjusted odds ratio' -> 'adjusted'. Reachable and consequential: 41 distinct held keywords in 11 topics are rewritten, and 25 held abstract sentences in 7 topics that carry such a keyword verbatim match no term, so _candidate_sentences drops them -- e.g. doac-vte-recurrence 'The primary efficacy outcome was recurrent symptomatic venous thromboembolism or death related to venous thromboembolism.' (measured 2026-09-25). Effect on a served absence state not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'protocol_compiler.py:search:6d4338abae-accept-2':
        "RX-OL27 (found 2026-09-25 by this plant): the separator class [-:–] has no em dash, so '**Estimand** — ...' is not read (the RX-EC2 miss, in a second parser). Reachable: parse_prose(protocols/colchicine-recurrent-pericarditis.md) returns estimand None, so compare() cannot check ESTIMAND_DIVERGENCE for that topic; masked today -- with the dash read, compare() returns the same divergence list (config RR agrees). The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'protocol_compiler.py:search:249cd61f88-accept-1':
        "RX-OL27 (found 2026-09-25 by this plant): same em-dash miss on '**Population** — ...': parse_prose returns population None for protocols/colchicine-recurrent-pericarditis.md, so compare() cannot check POPULATION_DIVERGENCE; masked today (config intention-to-treat agrees). The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'absence.py:_PRIMARY_RESULT-accept-2':
        "RX-OL22 (found 2026-09-25 by this plant): 'primary' must be followed directly by outcome/end point/event, so 'primary composite outcome' / 'primary efficacy outcome' is not a primary-result sentence and the primary-anchor pull-in in _candidate_sentences skips it. Reachable: 122 held abstract sentences (e.g. 'A primary composite outcome event occurred in 839 of 7356 patients'); effect on a served absence state not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'absence.py:_EFFECT-refuse-1':
        "RX-OL19 (found 2026-09-25 by this plant): under re.I 'OR' matches the conjunction 'or', so any 'X or Y ... 3.1' reads as an effect estimate. Reachable: 220 held abstract sentences fire ONLY through a conjunction 'or'. Direction: classify() then says the outcome's numbers ARE present (EXTRACTION_NOT_PERFORMED) instead of absent -- the module's stated safe direction, but a false 'present' claim; effect on a served state not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'absence.py:_ARMS-refuse-1':
        "RX-OL20 (found 2026-09-25 by this plant): 'N/MM' also matches a blood-pressure reading ('130/80 mm Hg') as arm counts. Reachable: 5 held abstract sentences fire only on a mm Hg reading; same safe direction as RX-OL19; effect not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'protocol_compiler.py:search:249cd61f88-accept-2':
        "RX-OL28 (found 2026-09-25 by this plant): the separator must follow the closing '**', so '**Population:** ...' is not read (the RX-EC1 miss, in a second parser). Reachable in 4 held protocols (denosumab-vertebral-fracture, esketamine-trd-madrs, melatonin-primary-insomnia-sol, semaglutide-obesity-weight); none of those lines carries analysis-set wording, so no population is lost today. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'pipeline.py:_PMID_LITERAL_RE-refuse-2':
        "RX-OL30 (found 2026-09-25 by this plant): the lookbehind only excludes a preceding digit, so the 8 digits of 'NCT00113685' are also read as a PMID literal. Reachable: 182 held files carry NCT-list queries, each adding spurious pmid_literal features; the query class cannot change (nct_literal already makes it IDENTIFIER_SEEDED). The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'absence.py:_COUNT_WITH_PERCENT-accept-3':
        "RX-OL21 (found 2026-09-25 by this plant): only '%' marks a percentage, so NEJM's older '452 patients (35.2 percent)' is not a count with its percentage. Latent: 0 held abstract sentences carry that exact form. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'gate.py:sub:0441b19e00-refuse-1':
        "RX-OL24 (found 2026-09-25 by this plant): every 19xx/20xx token is dropped as a publication year, so a count such as '2047 patients' escapes the 'every manuscript numeral is object-derived' check (fails open). Latent: 0 counts in that range beside patients/participants/events in the 32 held reviews' rendered manuscripts. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'gate.py:search:f3bc3e60aa-refuse-1':
        "RX-OL26 (found 2026-09-25 by this plant): any 'dose' / 'amendment' / 'approved' in the protocol satisfies 'documents a dose-selection rule', so 'low-dose aspirin' passes (fails open). Latent: 0 held reviews carry a dose_selection override, so the check never runs today. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'gate.py:_PARITY_EXCL_CUE-refuse-2':
        "RX-OL25 (found 2026-09-25 by this plant): the cue ignores negation, so 'SELECT was not excluded' names SELECT as excluded and a pooled SELECT raises a false L1 (fails closed). Latent: 0 held parity reasons negate a cue. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'protocol_compiler.py:search:cbbabbb69a-accept-2':
        "RX-OL29 (found 2026-09-25 by this plant): only the hyphenated 'double-blind' is read, so 'double blind, placebo-controlled' sets no AND masking. Latent: the 3 held protocols spelling it unhyphenated say 'double blinding is not required', where None is right. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'reason_audit.py:_ASSIGNED-accept-1':
        "RX-OL31 (found 2026-09-25 by this plant): the count must sit directly before '(were) assigned', so the common '4745 patients were randomly assigned to colchicine' gives no per-arm denominator. Reachable and consequential: 74 held abstract sentences use '<N> <noun> were assigned to', and allowing the noun changes _assignment_denominators for 43 held records (e.g. colchicine-postop-af 37640035: (None, None) -> (1608, 1601)), so _normalised_value falls back to a bare fraction or None there (measured 2026-09-25 with a scratch-patched pattern); effect on a served reason-audit row not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'consumer_consistency.py:_PUBLISHED_EFFECT_IN_SOURCE-accept-2':
        "RX-OL32 (found 2026-09-25 by this plant): the effect must be named in words (hazard / odds / risk / rate ratio, relative risk), so an abbreviated 'OR 0.34, 95% CI ...' / 'HR, 1.02; 95% CI ...' is not a published effect. Reachable and consequential: 3 of the 39 held reconstructed rows carry such a span and are not flagged EXTRACTED_RECONSTRUCTION_WHILE_PUBLISHED_EXISTS -- probiotics-aad-prevention PMID 18026577 (the same outcome's published OR 0.34, 95% CI 0.125 to 0.944) and two dpp4-mace-t2d PMID 30418475 rows (whose HR is the primary outcome's, not theirs). The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'reason_audit.py:_EXPLICIT_FRACTION-refuse-1':
        "RX-OL33 (found 2026-09-25 by this plant): 'N/M' also matches a blood-pressure threshold ('125/75 mmHg'), so with any group word the sentence reads as carrying a numeric outcome. Reachable: 1 held abstract sentence fires only on a mm Hg reading next to a group word; effect not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'consumer_consistency.py:search:6ecd1e4cdd-accept-1':
        "RX-OL34 (found 2026-09-25 by this plant): the count must sit directly before '(were) assigned', so '2366 patients were assigned to colchicine ...' gives no denominator (the RX-OL31 miss in a second parser). Latent: both held abstracts with a two-arm event-count sentence already yield denominators. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'consumer_consistency.py:search:5994968a29-accept-1':
        "RX-OL35 (found 2026-09-25 by this plant): 'to the' is required before both arms, so '2366 were assigned to colchicine and 2379 to placebo' gives no denominator. Latent: as RX-OL34. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'membership.py:_NEGATIVE_PARITY_RE-refuse-1':
        "RX-OL36 (found 2026-09-25 by this plant): the cue ignores negation, so 'SELECT was not excluded' makes a pooled SELECT a parity conflict (fails closed; the RX-OL25 miss in a second checker). Latent: 0 held parity reasons negate a cue. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'reason_audit.py:_NCT_OR_PMID-refuse-1':
        "RX-OL37 (found 2026-09-25 by this plant): any 6-9 digit run bounded by non-word characters is taken as a PMID, so 'ChiCTR-IOR-17012345' canonicalises to '17012345' (and a EudraCT number to its middle block). Latent: 0 held trial ids / labels name another registry. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'arm_object.py:_WEEK-accept-2':
        "RX-OL38 (found 2026-09-25 by this plant): '(\\d{1,3})[-\\s]?week\\b' has no plural, so 'at 12 weeks' / 'over 52 weeks' is not a timepoint. Reachable and consequential: 210 held records state their timepoint only as 'N weeks' and get timepoint NOT_DERIVABLE from arm_object._timepoint (measured 2026-09-25); effect on a served row not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'design_key.py:_ALT_RE-accept-2':
        "RX-OL39 (found 2026-09-25 by this plant): after the estimate only '(' or ',' may precede '95% CI', so the NEJM form 'hazard ratio, 0.60; 95% CI, 0.37 to 0.97' (and a bare '(0.70 to 0.90)') is not a published estimate. Reachable and consequential: 28 held pooled rows' sources state an effect+CI in that form and their design key gets no published_alternative (so _correlation_for_trial / decision_for_trial see none) -- e.g. denosumab-vertebral-fracture PMID 19671655, doac-vte-recurrence PMID 22449293 (measured 2026-09-25). The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'arm_object.py:search:1543b331b8-accept-1':
        "RX-OL40 (found 2026-09-25 by this plant): the semaglutide dose must be one of 2.4 / 1.0 / 1.7 / 25 / 50 mg, so 0.5, 7, 7.2 or 14 mg gives no dose (or a later listed dose replaces the first). Reachable and consequential: 22 held semaglutide+placebo records (e.g. SUSTAIN-6 27633186 'semaglutide (0.5 mg', 42207966 'semaglutide 7.2 mg') get a missing or different contrast dose; effect on a served row not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'trial_family.py:REGISTRY-accept-5':
        "RX-OL41 (found 2026-09-25 by this plant): only NCT / EudraCT / ISRCTN / jRCT / ACTRN numbers are registry ids, so ChiCTR, IRCT, CTRI (and UMIN, DRKS, PACTR) ids are dropped from registry_ids(). Reachable and consequential: 40 held (record, id) pairs, none of whose records carries a listed id (e.g. corticosteroids-cap-mortality 35598005 'ChiCTR2100045056', colchicine-postop-af 42132185 'IRCT20200328046886N6'), so family keying by registry id cannot see them. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'trial_family.py:REGISTRY-accept-6':
        'RX-OL41 (found 2026-09-25 by this plant): an IRCT id is not a registry id (see accept-5). The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.',
    'arm_object.py:_DOSE-accept-3':
        "RX-OL42 (found 2026-09-25 by this plant): the unit group ends in '\\b', and '%' followed by a space or end has no word boundary, so the '%' unit can never match ('0.9% sodium chloride'). Latent in effect: a working '%' would also pick lab values such as 'HbA1c 7.5%' as the first dose, so the fix is a requirement decision, not a one-character change. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'claimgraph.py:search:0a97f189e1-accept-1':
        "RX-OL43 (found 2026-09-25 by this plant): 'valid\\s+RCT\\b' has no plural, so 'N valid RCTs = ours' is not a named count. Latent: 0 held parity reasons use the plural. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'compat_direction.py:_HETERO_RE-refuse-1':
        "RX-OL44 (found 2026-09-25 by this plant): the word list ignores negation, so 'did not differ' / 'no heterogeneity' (and 'mixed-effects') read as a heterogeneity assertion. Latent: 0 held review fields fire only that way. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'page.py:search:2a82269e03-refuse-1':
        "RX-OL45 (found 2026-09-25 by this plant): naming an estimand ('risk ratio (RR)', 'hazard ratio') counts as the protocol carrying results, which would retract a genuine prospective-registration claim. Latent: 0 of the 32 held reviews' protocols are flagged by estimand naming alone. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'page.py:search:e9a52114b2-accept-2':
        "RX-OL46 (found 2026-09-25 by this plant): this surface's list omits '\\bHR\\b' / '\\bRR\\b' that the Reproducibility-row check (page.py:search:2a82269e03) has, so a protocol quoting 'HR 0.87' is prospective on one surface and not on the other. Latent: the two surfaces agree on all 32 held protocols. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'harms.py:_EFFECT_OR_COMPARISON-refuse-1':
        "RX-OL47 (found 2026-09-25 by this plant): under re.I 'OR' matches the conjunction 'or', and any number within 90 characters follows, so '... or glipizide 5 mg/day' reads as a reported effect (the RX-OL19 miss, looser). Reachable: 1513 held abstract sentences fire only through a conjunction 'or'; a harm whose terms match such a sentence is marked reported with a numeric signal. Effect on a served harm row not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'source_hierarchy.py:_EFFECT_CANDIDATE-accept-2':
        "RX-OL48 (found 2026-09-25 by this plant): only a two-digit level ('95%') may precede 'CI', so a non-inferiority '97.5% CI' result is not an effect candidate. Reachable: 4 held abstract sentences (ENGAGE AF-TIMI 48's edoxaban hazard ratios, the HFNC vs CPAP adjusted HR); effect on source ranking not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'claim.py:_ASSERT_SIG-refuse-1':
        "RX-OL49 (found 2026-09-25 by this plant): the negation guard looks only at the two words immediately before, so 'we did not find any statistically significant benefit' asserts significance. Reachable: that sentence is on the held omega3-cardiovascular-events page; masked today -- it is in none of the surfaces the census checks, so 0 contradictions either way (measured 2026-09-25). The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'ctgov_results.py:search:193897396a-accept-2':
        "RX-OL50 (found 2026-09-25 by this plant): the event noun must follow 'number of' directly, so 'Number of All-cause Hospitalizations (First and Recurrent)' is not an event-count title. Reachable phrasing: one held CT.gov outcome title; it matters only when that row's paramType is COUNT_OF_PARTICIPANTS -- not measured. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'verify.py:search:a74619243b-refuse-1':
        "RX-OL51 (found 2026-09-25 by this plant): _digits_in formats int(v), so a decimal value is looked up truncated and a count may match the integer part of another decimal: mean 12.4 is 'verified' by 'mean 12.9' (or 'HR 0.12'). Latent: 0 of the 123 held rows rendered 'verified' depend on it (measured 2026-09-25 by re-verifying each with the value required as its own number). The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'screen_entry.py:_CONTROL-refuse-1':
        "RX-OL52 (found 2026-09-25 by this plant): 'control' anywhere marks a control arm, so an active 'Intensive glucose control' arm is dropped from the active set. Latent: 0 held record interventions. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'fda.py:_SECTION_RE-refuse-2':
        "RX-OL53 (found 2026-09-25 by this plant): any '14' + whitespace opens a section, so '14 patients were enrolled' in section-14 prose starts a new section. Latent: no FDA label text is held. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    'propositions.py:search:3d174448cd-accept-1':
        "RX-OL54 (found 2026-09-25 by this plant): the count must be digits, so 'we pool four trials' gives no pooled count. Latent: the 1 held parity reason with this phrase uses a digit. The fix belongs to the owning lane (not the regex layer), filed 2026-09-25.",
    '_ARMP-refuse-2':
        "RX-X1 (found 2026-09-25 by this plant): in 'COUNT of DENOMINATOR patients (P%)' the pattern reads the DENOMINATOR as the count ('386 of 2373 patients (16.3%)' -> 2373). 5 of 20. Reachable: cache/dapagliflozin-hfpef-hosp/records.json#31535829 abstract sentence 4; downstream the percentage corroboration (2373/den vs 16.3%) usually rejects it, so the effect on a served row is masked, not measured. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_ARMP-refuse-3':
        "RX-X26 (found 2026-09-25 by this plant): same misreading after a slash ('2066/4602 (44.9%)' -> 4602). 3 of 20. Reachable: cache/omega3-cardiovascular-events/records.json#27749986 abstract sentence 27; masked downstream as RX-X1, not measured. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_ARMP-accept-1':
        "RX-X2 (found 2026-09-25 by this plant): the count must be digits, so 'nine (7.5%)' / 'four (8%)' / 'two (1%)' are not read. 3 of 20. Reachable: cache/probiotics-aad-prevention/records.json#18410562 abstract sentence 4 (nine (7.5%) vs 20 (17%): only one arm is read, so the pair is lost). A fix must also map the word to an int (_arm_counts does int(group(1))). Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_ARMP-accept-2':
        "RX-X3 (found 2026-09-25 by this plant): only patients/participants/cases/subjects may sit between the count and '(P%)', so '324 hospital deaths (34.1%)' / '1016 hospitalisations (82.3%)' are not read. 2 of 20. Reachable: cache/prone-positioning-ards-mortality/records.json#20197533 abstract sentence 8 (one arm of each pair lost). Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_ARMP-refuse-4':
        "RX-X4 (found 2026-09-25 by this plant): a digit inside a hyphenated name is read as a count ('Pro-2 (1.2%)' -> count 2). 1 of 20. Reachable: cache/probiotics-aad-prevention/records.json#20145608 abstract sentence 9. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_K-refuse-1':
        "RX-X6 (found 2026-09-25 by this plant): the count group is '[A-Za-z]+', so ANY word before 'RCTs' / 'randomized controlled trials' is taken as k ('searched for RCTs' -> 'for', 'Randomized controlled trials were eligible' -> 'Randomized'). 28 of 41. Reachable and consequential: _parse_k uses the FIRST match, so in 177 of 645 held abstracts with a _K match it returns None although a later match states a count (measured 2026-09-26); outputs/regex_layer/K_SHADOW.json already records 16 topics where the served k differs. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_K-accept-1':
        "RX-X7 (found 2026-09-25 by this plant): an adjective between the count and the noun ('six eligible RCTs') makes the adjective the count. 1 of 41. Reachable: cache/vitamin-d-acute-respiratory-infection/records.json#39993397 abstract sentence 1. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_K-accept-2':
        "RX-X8 (found 2026-09-25 by this plant): a hyphenated number word is read by its tail ('Fifty-five RCTs' -> 'five'), and _parse_k then SERVES the tail: 25 -> 5 (metformin-pcos-ovulation 42602369) and 28 -> 8 (omega3-cardiovascular-events 35905212) in held abstracts. 1 of 41 labelled (cache/denosumab-vertebral-fracture/records.json#36852077 abstract sentence 7). A fix must also extend _WORDNUM to compounds. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MEAN_SD-accept-2':
        "RX-X9 (found 2026-09-25 by this plant): 'mean (SD)' / 'mean [SD]' declared once, then bare 'X (Y)' / 'X [Y]', is never read. 12 of 31 (plus 3 items where a later arm uses it). Reachable: cache/probiotics-aad-prevention/records.json#11387176 abstract sentence 3. A fix needs sentence context (a served wrapper, as WholeNumbers). Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MEAN_SD-accept-3':
        "RX-X10 (found 2026-09-25 by this plant): a '%' on the mean before the SD marker ('45%±10%', '70.8% ± 46.9%', '9.3% [SD 1.1]') blocks the match. 6 of 31. Reachable: cache/spironolactone-hfref-mortality/records.json#41766708 abstract sentence 6. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MEAN_SD-accept-4':
        "RX-X11 (found 2026-09-25 by this plant): only days/hours/minutes/points may sit between mean and SD, so '60.7 years (SD 9.8)' / '32 mm Hg [SD 8]' are not read. 2 of 31. Reachable: cache/sglt2-primary-prevention-hf/records.json#42035781 abstract sentence 10. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MEAN_SD-accept-5':
        "RX-X12 (found 2026-09-25 by this plant): the SD marker must be '(SD Y)' with ':'/'=' only, so '[SD, 16]', '(SD, 16.3)' and '(±5.0)' are not read. 5 of 31. Reachable: cache/hfnc-vs-conventional-o2-reintubation/records.json#27706464 abstract sentence 8. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MEAN_SD-accept-6':
        "RX-X13 (found 2026-09-25 by this plant): the sign of a negative mean is dropped ('-9.59 ± 2.87%' -> 9.59). 2 of 31. Reachable and direction-flipping: cache/sglt2-primary-prevention-hf/records.json#33042004 abstract sentence 11 (-9.59 vs -1.87: the unsigned difference has the opposite sign); effect on a served row not measured. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MEAN_SD-refuse-1':
        "RX-X14 (found 2026-09-25 by this plant): '±' after a mean is read as an SD even when the sentence says it is a standard error or a 95% CI ('mean ± standard error of 291.9 ± 64.4'). 3 of 31. Reachable: cache/semaglutide-obesity-weight/records.json#42323166 abstract sentence 8 (extract_continuous's docstring says SE is NOT SD). A fix needs sentence context. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MEAN_SD-refuse-2':
        "RX-X15 (found 2026-09-25 by this plant): a visit window 'day 12 ± 2' is read as a mean ± SD. 1 of 31. Reachable: cache/doac-vte-recurrence/records.json#21136019 abstract sentence 5. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-1':
        "RX-X16 (found 2026-09-25 by this plant): 'median (IQR)' / 'median [IQR]' declared once, then bare 'X (a-b)' / 'X [a-b]', is never read. 12 of 34. Reachable: cache/corticosteroids-cap-mortality/records.json#40388163 abstract sentence 10. A fix needs sentence context (a served wrapper). Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-2':
        "RX-X17 (found 2026-09-25 by this plant): only days/hours/minutes/points may sit between the median and the bracket, so 'years', 'months', 'weeks', 'h', '%', 'mg/L' block it. 12 of 34. Reachable: cache/omega3-cardiovascular-events/records.json#18757090 abstract sentence 4 (median follow-up 3.9 years (IQR 3.0-4.5)). Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-3':
        "RX-X18 (found 2026-09-25 by this plant): 'median' must be followed directly by the value (only 'of' allowed), so 'the median duration of treatment was 19 days (IQR 4-40)' is not read. 15 of 34. Reachable: cache/esketamine-trd-madrs/records.json#40226655 abstract sentence 10. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-4':
        "RX-X19 (found 2026-09-25 by this plant): after 'IQR' / 'interquartile range' only ':' or '=' is allowed, so the common '(IQR, 2-7)' / '(interquartile range, 8 to 11)' is not read. 9 of 34. Reachable: cache/doac-vte-recurrence/records.json#19966341 abstract sentence 1. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-5':
        "RX-X20 (found 2026-09-25 by this plant): an IQR outside a bracket ('median age 54.0 years, IQR 47.0-61.0') is not read. 2 of 34. Reachable: cache/colchicine-recurrent-pericarditis/records.json#34051877 abstract sentence 14. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-6':
        "RX-X21 (found 2026-09-25 by this plant): negative values are not read ('-4.3 mg/L (IQR -1.1 to -14.1)'). 3 of 34. Reachable: cache/colchicine-secondary-cv-prevention/records.json#31284074 abstract sentence 6. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-7':
        "RX-X22 (found 2026-09-25 by this plant): bounds separated by a comma ('(-0.1, 1.3)') are not read. 2 of 34. Reachable: cache/colchicine-secondary-cv-prevention/records.json#41670023 abstract sentence 15. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-8':
        "RX-X23 (found 2026-09-25 by this plant): thousands separators ('41,102 [23,170 to 75,140]') are not read. 1 of 34. Reachable: cache/probiotics-aad-prevention/records.json#36289153 abstract sentence 10. A fix must also strip the comma before float(). Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-9':
        "RX-X24 (found 2026-09-25 by this plant): a comma after 'median' ('median, 2 [interquartile range, 2-3]') blocks it. 1 of 34. Reachable: cache/doac-vte-recurrence/records.json#30453352 abstract sentence 6. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-10':
        "RX-X25 (found 2026-09-25 by this plant): a value with an explicit '(IQR ...)' but no 'median' directly before it (the second arm: '3 days (IQR 2-6) versus 4 days (IQR 2-7)') is not read, so a two-arm comparison loses an arm. 6 of 34. Reachable: cache/hfnc-vs-conventional-o2-reintubation/records.json#28393258 abstract sentence 13. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
    '_MED_IQR-accept-11':
        "RX-X37 (found 2026-09-25 by this plant): the nested label 'interquartile range (IQR) 47-70' is not read. 2 of 34. Reachable: cache/dapagliflozin-hfpef-hosp/records.json#41614664 abstract sentence 6. Fix is in pinned code (harness/extract.py); candidate regex in outputs/regex_layer/R4_CANDIDATE_FIXES.md; the served radius is not measured.",
}
