"""Build docs/offline/requirements.lock and docs/offline/wheels.json from PyPI's published digests.

MEASURE-TIME ONLY (network): reads https://pypi.org/pypi/<name>/<version>/json for each pinned distribution and
records, per target platform, the wheel filename, its PyPI-published sha256, size and download URL. Nothing here
runs during replay; scripts/replay_offline.py denies the network and refuses any runtime distribution whose version
is not pinned here. `pip install --require-hashes -r docs/offline/requirements.lock` accepts exactly these wheels
and nothing else (pip checks each downloaded or local wheel against the listed digests).

Targets are CPython 3.13 on Windows x86-64, Linux x86-64 (manylinux) and macOS arm64. Wheel BINARIES are not
vendored into the repository (that choice -- ~100 MB of binaries in git history -- is the maintainer's); the lock
names exactly which bytes are acceptable, so a fetched or locally mirrored wheel is verified, never trusted.
"""
from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PINS = {  # the distributions the replay and its verification tests load (observed: scripts/replay_offline.py)
    "numpy": "2.4.4", "scipy": "1.17.1", "pytest": "9.0.3", "pluggy": "1.6.0", "iniconfig": "2.3.0",
    "packaging": "26.0", "Pygments": "2.19.2", "colorama": "0.4.6", "Cython": "3.2.8",
    "setuptools": "83.0.0", "charset-normalizer": "3.4.7", "openpyxl": "3.1.5", "et-xmlfile": "2.0.0",
}
TARGETS = {
    "win_amd64": re.compile(r"-cp313-cp313-win_amd64\.whl$"),
    "linux_x86_64": re.compile(r"-cp313-cp313-manylinux[^-]*x86_64[^-]*\.whl$"),
    "macos_arm64": re.compile(r"-cp313-cp313-macosx_\d+_\d+_arm64\.whl$"),
}
PURE = re.compile(r"-py3-none-any\.whl$|-py2\.py3-none-any\.whl$")


def wheels_for(name: str, version: str) -> list[dict]:
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=60) as r:
        data = json.load(r)
    urls = [u for u in data["urls"] if u["packagetype"] == "bdist_wheel"]
    pure = [u for u in urls if PURE.search(u["filename"])]
    picked = []
    if pure:
        picked.append(("any", pure[0]))
    else:
        for target, rx in TARGETS.items():
            cands = sorted((u for u in urls if rx.search(u["filename"])), key=lambda u: u["filename"])
            if not cands:
                raise SystemExit(f"REFUSED: no {target} cp313 wheel for {name}=={version}")
            picked.append((target, cands[-1]))
    return [{"name": name, "version": version, "target": t, "file": u["filename"],
             "sha256": u["digests"]["sha256"], "bytes": u["size"], "url": u["url"]} for t, u in picked]


def main() -> int:
    wheels = [w for name, ver in PINS.items() for w in wheels_for(name, ver)]
    lines = ["# GENERATED by scripts/build_offline_lock.py from PyPI-published digests; never hand-maintain.",
             "# CPython 3.13; wheels for Windows x86-64, Linux x86-64 (manylinux), macOS arm64.",
             "# Install: python -m pip install --require-hashes -r docs/offline/requirements.lock"]
    for name, ver in PINS.items():
        hashes = " ".join(f"--hash=sha256:{w['sha256']}" for w in wheels if w["name"] == name)
        lines.append(f"{name}=={ver} {hashes}")
    out = ROOT / "docs" / "offline"
    out.mkdir(parents=True, exist_ok=True)
    (out / "requirements.lock").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    (out / "wheels.json").write_text(json.dumps(wheels, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"locked {len(PINS)} distributions, {len(wheels)} wheels")
    return 0


if __name__ == "__main__":
    sys.exit(main())
