"""One self-contained Markdown file for the external auditor (Mahmood, 8 Oct: "for the auditor give me as downloadable MD
file in chat and then auditor will do one by one").

Reads COMMITTED files only, through `git show <commit>:<path>`, so the output is reproducible from two commit ids:
  --live    the commit the site serves (the page bytes are compared with the live site separately; see the header)
  --notes   the commit holding outputs/pva-2026-10-08/REVIEW_TABS_HANDOVER.md (the known open issues)

  python scripts/build_auditor_md.py --live <sha> --notes <sha> --out AUDITOR_PACK.md

Samples (fixed here, before any draw): per review, up to 3 extraction rows at random.Random(f"20261008:{slug}") from the
rows the gate lets a page show, and 5 screening records at random.Random(f"20261008:{slug}:screen").
"""
from __future__ import annotations

import argparse
import hashlib
import json
import random
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))
from harness import review_tabs as T  # noqa: E402
from harness.provenance_class import served_class  # noqa: E402
import review_tab_inventory as INV  # noqa: E402

SITE = "https://mahmood726-cyber.github.io/meta-harness/"
REPO = "https://github.com/mahmood726-cyber/meta-harness"
SEED = 20261008
N_EXTRACT, N_SCREEN = 3, 5
# where each required element sits on the LIVE (legacy, 12-tab) page
LIVE_TAB = {"protocol": "Protocol", "search": "Search (counts and PRISMA flow: Screening)", "screening": "Screening",
            "included": "Screening (Trial families) and Results", "extraction": "Results (per-trial rows, Source column) and Harms",
            "riskofbias": "Risk of bias", "analysis": "Results (model, heterogeneity) and Manuscript (forest plot)",
            "results": "Results and Manuscript", "comparator": "Comparator", "changes": "Reproducibility (Result changed notices)",
            "reproduce": "Reproducibility and Verify this page"}


def git(*a) -> str:
    return subprocess.run(["git", "-C", str(ROOT), *a], capture_output=True, text=True, encoding="utf-8", errors="replace",
                          check=True).stdout


def show(c, p):
    return git("show", f"{c}:{p}")


def j(c, p):
    return json.loads(show(c, p))


def md(x) -> str:
    return str("" if x is None else x).replace("|", "\\|").replace("\n", " ").strip()


def build(live: str, notes: str, live_check: str) -> str:
    live = git("rev-parse", live).strip()
    notes = git("rev-parse", notes).strip()
    slugs = sorted(p.split("/")[2] for p in git("ls-tree", "-r", "--name-only", live, "docs/reviews").split()
                   if p.endswith("/review.json"))
    ab = j(live, "registry/g1_abandoned.json")
    abandoned = {t["slug"]: t for t in ab["topics"] if t.get("state") == "ABANDONED_BY_DECISION"}
    decisions = [d["id"] for d in j(live, "registry/g1_decisions.json")["decisions"]]
    notices = j(live, "docs/result_changes.json")["notices"]
    reads = j(live, "registry/provenance_recorded_reads.json").get("reads") or {}
    # the held-record index AT THE LIVE COMMIT (what the served page checked against); unreadable -> UNKNOWN rows
    try:
        held = frozenset(j(live, "registry/held_record_ids.json")["ids"])
    except (subprocess.CalledProcessError, ValueError, KeyError):
        held = None
    order = [s for s in slugs if s not in abandoned] + [s for s in slugs if s in abandoned]
    lc_raw = Path(live_check).read_bytes()
    lc = json.loads(lc_raw)
    if lc.get("commit") != live:
        raise SystemExit(f"REFUSED: the live check is of {lc.get('commit')}, not {live}")
    new_tabs = bool(lc["live"]) and lc["reviews_with_tab_contract"] == lc["reviews_n"]
    out = [f"# Meta-harness: external audit pack (one review at a time)\n",
           f"Generated by `python scripts/build_auditor_md.py --live {live[:12]} --notes {notes[:12]} --live-check "
           f"{Path(live_check).name} --out AUDITOR_PACK.md` from committed files only (the generator is "
           "`scripts/build_auditor_md.py`; the live check is `scripts/check_live_deploy.py`).\n",
           f"**What is live** (fetched {lc['checked_utc']}; check file sha256 `{hashlib.sha256(lc_raw).hexdigest()[:16]}`): "
           f"{lc['reviews_match']} of {lc['reviews_n']} review pages served byte-identical to `{live[:12]}`; "
           f"{lc['reviews_with_tab_contract']} carry the RapidMeta tab set; `/audit/` returned {lc['audit_status']}"
           + (" and matches the commit." if lc["audit_match"] else ".") + "\n"]
    if not new_tabs:
        out.append("**The new RapidMeta tab set is NOT live.** Every URL below is a live page; each checklist item names the "
                   "live tab where that content sits today.\n")
    # ------------------------------------------------------------------ 1. guide
    out.append("""## 1. Guide

**What the harness is.** A reproducible meta-analysis pipeline. Each review is built by committed code from a committed
protocol and a committed cache of open sources (PubMed, ClinicalTrials.gov / AACT, open-access full text), and served at a
stable URL. Every served pooled number is meant to trace to a passage in a held source; each page carries a certificate of
digests, and `python scripts/reproduce_review.py <slug>` rebuilds a review offline and fails on any byte difference.

**What to check, per review.** Work through the numbered sections below in order. For each review: open the live page,
confirm its `review_sha256` (page header, "Pinned audit identity"), then tick each tab item. For each sampled extraction
row, compare the passage with the source record (PMID -> PubMed) and recompute the digest:
`python -c "import hashlib,sys;print(hashlib.sha256(sys.argv[1].encode()).hexdigest())" "<passage>"`.
For each sampled screening record, read the record at its source and judge the decision and rule.

**How to record findings.** One row per finding in the review's findings block: what the page states (quote it), which tab,
the evidence (quote the source, with its link), and severity: **changes a served number** / **changes served wording** /
**record only**. Always cite the `review_sha256` you audited: a page is identified by it, not by its URL.

**Status labels.** **ACTIVE**: counted in the G1 comparison. **ABANDONED BY DECISION**: Mahmood's decision of 7 Oct (rule
`G1-ABANDON-v1`, registry/g1_abandoned.json): the page stays served and auditable but can never count as matched.

**Limits, stated plainly.**
- The harness's gates have **no measured precision**: no error rate has been estimated for any gate, so a page that passes
  every gate is not shown to be correct.
- The tab checks report that an element is **SHOWN, not that it is correct**. A ticked "present" is where your audit starts.
- Replay proves the same inputs give the same outputs; it does not prove the inputs are right or the search complete.
- Agreement with a published meta-analysis (G1) is a comparison, not independent corroboration.
- Risk-of-bias judgements are rule-based; the recorded dual-model sign-off decision D11 requires is not yet applied.
- Known open issues are listed in section 4: do not spend time re-discovering them; do report anything they miss.
""")
    # ------------------------------------------------------------------ 2. reviews
    out.append(f"## 2. The {len(order)} reviews ({len(order) - len(abandoned)} active first, then {len(abandoned)} abandoned)\n")
    for i, slug in enumerate(order, 1):
        r = j(live, f"docs/reviews/{slug}/review.json")
        m = j(live, f"docs/reviews/{slug}/manifest.json")
        page = show(live, f"docs/reviews/{slug}/index.html")
        try:
            gs = j(live, f"outputs/k_gap/g1/{slug}.json").get("g1_status") or {}
            g1 = (gs.get("state") or "not recorded") + (f" (unmet: {', '.join(gs.get('unmet') or [])})" if gs.get("unmet") else "")
        except subprocess.CalledProcessError:
            g1 = "not recorded"
        st = "ABANDONED BY DECISION" if slug in abandoned else "ACTIVE"
        inv = INV.check(slug, page, r, notices, decisions)
        out.append(f"### 2.{i} {md(r.get('title'))}\n")
        out.append(f"- Live page: {SITE}reviews/{slug}/index.html")
        out.append(f"- Status: **{st}**" + (f" -- {md(abandoned[slug].get('reason'))}" if slug in abandoned else ""))
        out.append(f"- review_sha256: `{m.get('review_sha256')}`  (served page html_sha256 `{m.get('html_sha256')}`)")
        out.append(f"- G1 status: **{md(g1)}** ({SITE}g1/index.html#{slug})")
        out.append(f"- Certificate: {SITE}reviews/{slug}/CERTIFICATE.json · replay: `python scripts/reproduce_review.py {slug}`\n")
        out.append("**Checklist** (*shown on the live page?* is a marker check: an element is SHOWN, not shown to be correct; "
                   "'stated reason' = the tab says why the element is absent)\n")
        out.append("| ✓ | tab | where on the live page | shown on the live page? |\n|---|---|---|---|")
        for tid, label in INV.REQUIRED:
            v = inv[tid]
            el = v["elements"]
            reasoned = {re.sub(r" \(.*\)$", "", k) for k in v.get("reasoned") or []}
            missing = [re.sub(r" \(.*\)$", "", k) for k, ok in el.items() if not ok]
            parts = [("stated reason: " if k in reasoned else "not shown: ") + k for k in missing]
            shown = "all elements" if not missing else "; ".join(parts)
            where = (f"{label} tab" if v.get("dedicated_tab") else LIVE_TAB[tid])
            out.append(f"| ☐ | {label} | {where} | {md(shown)} |")
        rows = [x for x in _rows(r, slug, reads, held)]
        rng = random.Random(f"{SEED}:{slug}")
        pick = sorted(rng.sample(range(len(rows)), min(N_EXTRACT, len(rows))))
        out.append(f"\n**Extraction sample** ({len(pick)} of {len(rows)} shown rows; seed `{SEED}:{slug}`)\n")
        if not pick:
            out.append("_No row may be shown: every outcome of this review is withheld by the gate (see Results)._\n")
        for k in pick:
            x = rows[k]
            pm = T._ids({"id": x["id"], "label": x["trial"]})[0]
            row = (f" · row: {SITE}reviews/{slug}/index.html#{x['anchor']}" if new_tabs else "")
            out.append(f"- ☐ **{md(x['outcome'])} / {md(x['trial'])}** -- {md(x['value'])} · provenance `{md(x['provenance'])}` · "
                       f"class **{x['class']}** · state: {md(x['state'])}"
                       + (f" · https://pubmed.ncbi.nlm.nih.gov/{pm}/" if pm else "") + row)
            out.append(f"  - passage: > {md(x['passage'])}")
            out.append(f"  - sha256: `{x['passage_sha256']}`")
        recs = [x for x in ((r.get("screening") or {}).get("records") or []) if x.get("id")]
        srng = random.Random(f"{SEED}:{slug}:screen")
        spick = sorted(srng.sample(range(len(recs)), min(N_SCREEN, len(recs))))
        out.append(f"\n**Screening sample** ({len(spick)} of {len(recs)} records; seed `{SEED}:{slug}:screen`)\n")
        out.append("| ✓ | record | decision | rule | reason given |\n|---|---|---|---|---|")
        for k in spick:
            x = recs[k]
            out.append(f"| ☐ | `{md(x.get('id'))}` | {md(x.get('decision'))} | {md(x.get('rule_id'))} | {md(x.get('reason'))} |")
        out.append("\n**Findings**\n\n| # | finding | tab | evidence quote (page and source) | severity |\n|---|---|---|---|---|\n"
                   "| 1 |  |  |  |  |\n| 2 |  |  |  |  |\n| 3 |  |  |  |  |\n")
    # ------------------------------------------------------------------ 3. never served
    out.append("## 3. Registered but never served (6)\n")
    served = set(slugs)
    for p in sorted(git("ls-tree", "--name-only", live, "topics/").split()):
        s = p.split("/")[-1][:-5]
        if s in served:
            continue
        key = {"zinc-common-cold-duration": "zinc", "vitamin-d-acute-respiratory-infection": "vitamin",
               "prone-positioning-ards-mortality": "prone", "hfnc-vs-conventional-o2-reintubation": "hfnc",
               "azithromycin-copd-exacerbation": "azithro", "antibiotics-vs-appendectomy-appendicitis": "antibiotics ("}.get(s, s)
        log = [ln for ln in git("log", live, "--format=%h %ad %s", "--date=short", "-i", "--grep=declin").splitlines()
               if key.lower() in ln.lower()]
        if log:
            out.append(f"- `{s}` -- declined: {md(log[-1][:200])} (latest: {md(log[0][:120])})")
        else:
            out.append(f"- `{s}` -- **no recorded reason** (registered; no decline commit found)")
    # ------------------------------------------------------------------ 4. known open issues
    ho = show(notes, "outputs/pva-2026-10-08/REVIEW_TABS_HANDOVER.md")
    body = ho.split("\n## ", 1)[1] if "\n## " in ho else ho
    out.append("\n## 4. Known open issues (do not re-discover; H1 needs a decision)\n")
    out.append(f"From `outputs/pva-2026-10-08/REVIEW_TABS_HANDOVER.md` at `{notes[:12]}`, verbatim:\n")
    out.append("## " + body)
    return "\n".join(out).rstrip() + "\n"


def _rows(r, slug, reads, held):
    rows = []
    for oi, o in enumerate(r.get("outcomes") or []):
        if T._gated(o):
            continue
        for ti, t in enumerate(o.get("trials") or []):
            if held is None:
                cls = "UNKNOWN"
            else:
                cls, why, recs = served_class(t, slug, o.get("name"), held.__contains__, reads, str(ROOT))
            rows.append({"anchor": f"x{oi}-{ti}", "outcome": o.get("name"), "trial": t.get("label"), "id": t.get("id"), "value": T._value(t),
                         "provenance": t.get("provenance"), "class": cls, "state": T.outcome_state(o),
                         "passage": T.passage(t), "passage_sha256": T.passage_sha256(t)})
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--live", required=True)
    ap.add_argument("--notes", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--live-check", required=True, help="JSON from scripts/check_live_deploy.py --commit <live>")
    a = ap.parse_args()
    text = build(a.live, a.notes, a.live_check)
    Path(a.out).write_text(text, encoding="utf-8", newline="\n")
    sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
    Path(a.out + ".sha256").write_text(f"{sha}  {Path(a.out).name}\n", encoding="utf-8", newline="\n")
    print(f"wrote {a.out} ({len(text)} chars, sha256 {sha})")


if __name__ == "__main__":
    main()
