"""The G1 SEARCH + SCREEN RECALL AUDIT report, built ONLY from the committed artefacts of this lane (no number typed by
hand): SEARCH_SCREEN_AUDIT.json, search_miss_probe.json, search_volume_probe.json, rrl_probe.json, query_audit.json,
screen_dual_review.json (v2) + _v1, screen_radius_review.json, screen_fix_radius_*.json, amendments.json.

Every screen miss (an ELIGIBLE comparator trial our search identified that our screen excluded) is typed, first match:
  FIXED_ON_BRANCH        served exclude -> this branch's screener includes it
  POST_SCREEN_STAGE      X-DEDUP / X-CONTRAST (duplicate / contrast handling after the screen; not an eligibility call)
  DESIGN_NOT_STATED      X-DESIGN on absence ('no placebo/double-blind/masked in text'): verification owed (registry
                         masking / full text), never a scope difference
  SCREEN_FALSE_EXCLUSION adjudicated ELIGIBLE by the recorded dual review (v2) and still excluded on this branch
  PROTOCOL_EXCLUSION     adjudicated INELIGIBLE (the registered criteria exclude it)
  UNRESOLVED             the reader and the adjudicator could not decide from the held record

  python scripts/g1_search_screen_report.py   -> outputs/search_audit/SEARCH_SCREEN_REPORT.md
"""
from __future__ import annotations

import collections
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SA = os.path.join(ROOT, "outputs", "search_audit")


def _j(n):
    p = os.path.join(SA, n)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else {}


def screen_type(r):
    ex = r.get("screen_exclusion") or {}
    dr = r.get("dual_review") or {}
    if r.get("screen_branch") == "INCLUDED":
        return "FIXED_ON_BRANCH"
    if ex.get("rule_id") in ("X-DEDUP", "X-CONTRAST"):
        return "POST_SCREEN_STAGE"
    if ex.get("rule_id") == "X-DESIGN" and "no 'placebo'" in (ex.get("span") or ""):
        return "DESIGN_NOT_STATED"
    if dr.get("final") == "ELIGIBLE":
        return "SCREEN_FALSE_EXCLUSION"
    if dr.get("final") == "INELIGIBLE":
        return "PROTOCOL_EXCLUSION"
    return "UNRESOLVED"


def main():
    a = _j("SEARCH_SCREEN_AUDIT.json")
    vol = _j("search_volume_probe.json").get("topics", {})
    qa = _j("query_audit.json").get("topics", {})
    dv1 = _j("screen_dual_review_v1.json")
    rr = _j("screen_radius_review.json")
    T = a["totals"]
    L = ["# G1 search + screen recall audit", "",
         f"Branch g1/search-screen-audit. Inputs pinned: acq/k-gap {a['inputs']['acq_commit'][:10]}. Every number below is "
         f"read from the committed artefacts in outputs/search_audit/ (this file is generated by "
         f"scripts/g1_search_screen_report.py).", "",
         "## What was counted", "",
         f"Comparator trials across the 32 topics: {T['N_comparator']}. Kinds: {a['kinds']['ELIGIBLE']} ELIGIBLE (the "
         f"recall denominator, equal to the tracker's N_eligible on every topic), {a['kinds']['SCREEN_NAMED']} left the "
         f"eligible set because OUR screen excluded them (re-checked below, never assumed correct), "
         f"{a['kinds']['NAMED_OTHER']} other named differences (outcome set, estimand).", "",
         "## Search", "",
         f"- Registered search (PubMed + CT.gov as run): **{T['search_recall']['n']} of {T['search_recall']['N']}** eligible "
         f"trials identified.",
         f"- Plus other published metas' reference lists already held: {T['search_or_rrl_other_recall']['n']} of "
         f"{T['search_or_rrl_other_recall']['N']}.",
         f"- After this branch's identification fixes (counterfactual, recorded probes): **{T['fixed_identification_recall']['n']} "
         f"of {T['fixed_identification_recall']['N']}**; {T['fixed_identification_recall_independent']['n']} of "
         f"{T['fixed_identification_recall_independent']['N']} without the comparator's own reference list (circular as a "
         f"measure: it lists its trials by construction).",
         f"- Search misses, typed by the recorded probe: " + ", ".join(f"{k} {v}" for k, v in sorted(T["miss_types"].items())) + ".",
         ""]
    trunc = [(s, v["ctgov_retained"], v["ctgov_count_today"]) for s, v in sorted(vol.items()) if v.get("ctgov_truncated")]
    L += [f"**Class defect 1, CT.gov silently capped at 30** ({len(trunc)} of {len(vol)} topics): "
          + "; ".join(f"{s} {r} of {n}" for s, r, n in trunc) + ". Fixed (harness.fetch pagination, plant).", "",
          "**Class defect 2, REVIEW_REFERENCE_LIST not standing**: only the comparator's PubMed elink list ran by default. "
          "Now standing for every topic: comparator backward (PubMed + Europe PMC) and forward citation, plus up to 2 other "
          "open metas' reference lists (plant; declared by dated amendment A1 on every topic).", "",
          "**Query gaps**: registered PubMed queries are mostly hand-written keyword or title-word queries. One blind recorded "
          "query audit per topic (the proposer never saw the comparator's trials):", ""]
    acc = [(s, q) for s, q in sorted(qa.items()) if str((q.get("validation") or {}).get("verdict", "")).startswith("ACCEPT")]
    cap = [(s, q) for s, q in sorted(qa.items()) if "volume" in str((q.get("validation") or {}).get("verdict", ""))]
    L += ["| Topic | Registered queries match | + proposed (union) | Proposed volume | Verdict |", "|---|---|---|---|---|"]
    for s, q in acc + cap:
        v = q["validation"]
        L.append(f"| {s} | {v['recall_current']['n']}/{v['recall_current']['N']} | {v['recall_union']['n']}/"
                 f"{v['recall_union']['N']} | {v['proposed_pubmed_count']} | {v['verdict']} |")
    L += ["", f"{len(acc)} accepted and ADDED by dated amendment A3; {len(cap)} gain recall but exceed the 5,000-record volume "
          f"cap -- **decision for Mahmood** (the cap is this lane's threshold, not a rule); "
          f"{len(qa) - len(acc) - len(cap)} show no recall gain.", ""]
    # screen
    dr = a.get("dual_review") or {}
    L += ["## Screen", "",
          f"- Screen recall (eligible trials our search identified, then included by our screen): served "
          f"**{T['screen_recall']['n']} of {T['screen_recall']['N']}**; under this branch's screener "
          f"**{T['screen_recall_branch']['n']} of {T['screen_recall_branch']['N']}**.",
          f"- Recorded dual review v2 (second screener: {dr.get('reader_model')}; adjudicator: {dr.get('adjudicator_model')}; "
          f"both see the registered criteria including the exclusion lists): {dr.get('n_items')} items "
          f"({dr.get('tally')}). **Cohen's kappa, rule screener vs reader: {(dr.get('kappa_rule_vs_reader') or {}).get('kappa')}** "
          f"on {(dr.get('kappa_rule_vs_reader') or {}).get('n_decided')} decided items "
          f"({(dr.get('kappa_rule_vs_reader') or {}).get('n_undecided')} the reader could not decide from the record).",
          f"- v1 (reader saw only the summary criteria, not the registered exclusion lists): kappa "
          f"{(dv1.get('kappa_rule_vs_reader') or {}).get('kappa')}; kept for the record -- the two differ because v1 judged "
          f"protocol-excluded populations (CABG, assisted reproduction, eye disease) against a looser standard.", ""]
    rows = [(t["slug"], r) for t in a["topics"] for r in t["trials"]
            if r["kind"] == "ELIGIBLE" and r["search"].startswith("IDENTIFIED") and r["screen"] == "EXCLUDED"]
    types = collections.Counter(screen_type(r) for _, r in rows)
    L += [f"Eligible trials our screen EXCLUDED (served): {len(rows)}. Typed: " + ", ".join(f"{k} {v}" for k, v in
                                                                                            types.most_common()) + ".", "",
          "| Topic | Trial | Rule (served) | Dual review | Branch | Type |", "|---|---|---|---|---|---|"]
    for s, r in sorted(rows, key=lambda x: (screen_type(x[1]), x[0])):
        ex = r.get("screen_exclusion") or {}
        L.append(f"| {s} | {r['label']} | {ex.get('rule_id')} | {(r.get('dual_review') or {}).get('final')} | "
                 f"{r.get('screen_branch')} | {screen_type(r)} |")
    named = [(t["slug"], r) for t in a["topics"] for r in t["trials"] if r["kind"] == "SCREEN_NAMED"]
    nt = collections.Counter((r.get("dual_review") or {}).get("final") or "NOT_READ" for _, r in named)
    v1n = collections.Counter(i.get("final") for i in dv1.get("items") or [] if i.get("kind") == "SCREEN_NAMED")
    L += ["", f"Screen-named exclusions re-checked ({len(named)}): dual review v2 final {dict(nt)}"
          + (f" -- every one confirmed by the second screener (v1, whose reader did not see the registered exclusion "
             f"lists, had {v1n.get('ELIGIBLE', 0)} adjudicated eligible: an instrument gap, not a screener error)"
             if set(nt) == {"INELIGIBLE"} else
             "; any adjudicated ELIGIBLE is a protocol-term exclusion whose change is an eligibility amendment") + ".", "",
          "### Screen fixes on this branch (each with plants that fail before, and a measured radius over all 3,201 held "
          "decisions)", "",
          "- **A, enrolled-population sentence**: a population term in an abstract sentence stating THIS study's "
          "enrolment counts (LoDoCo, Nidorf 2013). LoDoCo itself then stops at X3: our protocol requires placebo, LoDoCo "
          "randomised 'no colchicine' -- a protocol scope difference, not a screener error.",
          "- **C, X1 reason matches its span**: 16 X1s said 'not an RCT' while citing PubMed type RCT; the title marker that "
          "fired is now named and quoted. 0 decisions change.",
          "- **D, condition is the outcome**: when the registered population terms are the outcome (probiotics: 'AAD'), "
          "the population inclusion check reads sentences about THIS study (never background). A whole-abstract draft was "
          "rejected by the recorded radius review (4 of 12 contradicted).",
          "- **E, economic evaluation title marker**: a health-economic evaluation alongside a trial is a secondary report.",
          f"- Recorded radius review of every non-comparator flip: {rr.get('tally')}.", "",
          "## Decisions for Mahmood (not taken by this lane)", "",
          "1. **Volume cap**: the 7 topics whose blind concept query gains recall above 5,000 records (table above).",
          "2. **Secondary-report family routing** (COPPS POAF, the substudy class): Codex NR-C28 showed the narrow 'admit a "
          "PubMed-RCT substudy' rule is unsafe; a family-routing stage is needed (notice COLCHICINE_POSTOP_AF_GAPS).",
          "3. **Probiotics eligibility vocabulary**: the registered population 'patients receiving antibiotics' has no "
          "screening term; H. pylori-eradication and C. difficile trials stay X2 (Cindoruk, Plomer, Plummer, Shimbo). "
          "Adding population terms is an eligibility amendment.",
          "4. **Served pages**: the amendments and screen fixes change what a rebuild serves; no page was regenerated here.",
          ""]
    open(os.path.join(SA, "SEARCH_SCREEN_REPORT.md"), "w", encoding="utf-8", newline="\n").write("\n".join(L))
    print("\n".join(L[:30]))


if __name__ == "__main__":
    main()
