"""G1 MATCH, tocilizumab vs WHO REACT 2021: run g1/tocilizumab.py offline over held bytes and write the result.

  python scripts/g1_tocilizumab.py            -> g1/data/tocilizumab_g1.json (+ a summary on stdout)
  python scripts/g1_tocilizumab.py --aact     -> first rebuild g1/data/aact_toci.json from the local AACT snapshot
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from g1 import tocilizumab as g  # noqa: E402

OUT = os.path.join(ROOT, "g1", "data", "tocilizumab_g1.json")


def main(argv):
    if "--aact" in argv:
        ex = g.build_aact_extract(sorted({v[0] for v in g.IDENTITY.values() if v[0]}))
        open(g.AACT_FILE, "w", encoding="utf-8", newline="\n").write(json.dumps(ex, indent=1, ensure_ascii=False) + "\n")
    r = g.run()
    open(OUT, "w", encoding="utf-8", newline="\n").write(json.dumps(r, indent=1, ensure_ascii=False) + "\n")
    pc, pr = r["positive_control"], r["comparator"]["printed"]
    print(f"positive control: REACT's rows -> FE OR {pc['or']} ({pc['lo']}-{pc['hi']}), printed {pr['estimate']} "
          f"({pr['ci_low']}-{pr['ci_high']})")
    print("trials:", r["tally"], "| established vs REACT:", r["vs_react"], "| k matched:", r["k_matched"], "of 19")
    print("pooled, established primary rows:", r["pool_ours_established"], "| REACT, same trials:", r["pool_react_same_trials"])
    open(os.path.join(ROOT, "g1", "TOCILIZUMAB_G1.md"), "w", encoding="utf-8", newline="\n").write(markdown(r))
    return 0


def markdown(r) -> str:
    sys.path.insert(0, os.path.join(ROOT, "scripts"))
    import g1_toci_tracker as tr                      # the routed tracker entry: one definition of k matched
    d = tr.build()
    route = {t["label"]: t for t in d["trials"]}
    cov = d["coverage"]
    pc, pr = r["positive_control"], r["comparator"]["printed"]
    po, pre = r["pool_ours_established"] or {}, r["pool_react_same_trials"] or {}
    lines = ["# G1 MATCH: tocilizumab 28-day mortality vs WHO REACT 2021 (generated by scripts/g1_tocilizumab.py)", "",
             f"- **Comparator**: REACT (PMID {r['comparator']['pmid']}), 19 tocilizumab trials, FE OR {pr['estimate']} "
             f"({pr['ci_low']}-{pr['ci_high']}). Its rows are the TARGET only: never a source, never in k matched.",
             f"- **Positive control**: REACT's own 19 rows -> FE OR {pc['or']} ({pc['lo']}-{pc['hi']}).",
             f"- **k matched: {d['k_matched']} of 19** -- a verified typed day-28 tuple, by route "
             + ", ".join(f"{k} {v}" for k, v in cov["k_matched_by_route"].items())
             + f"; {round(100 * cov['participant_share'])}% of REACT's participants. PRIMARY = two primaries, or one "
             "bound primary that STATES the counts (2 Oct); TWO_SOURCE = a primary + a REACT-independent meta; "
             "SECONDARY_SINGLE = a REACT-independent, self-reproducing meta row typed day 28 by the trial's own primary "
             f"(3 Oct). Matcher states ESTABLISHED by two sources: {r['k_matched']}.",
             f"- **States**: {r['tally']}. REACT rows that are a paper's SAFETY-population count: "
             f"{r['react_rows_that_are_safety_counts'] or 'none'}.",
             f"- **Coverage-limited reconciliation, NOT a finding.** On the {po.get('k_informative')} established trials "
             f"only, our rows pool to OR {po.get('or')} ({po.get('lo')}-{po.get('hi')}) and REACT's rows for the same "
             f"trials to OR {pre.get('or')} ({pre.get('lo')}-{pre.get('hi')}): this checks that our rows reproduce "
             f"REACT's on those trials. It is not an estimate of tocilizumab's effect: the largest trials not matched ("
             + ", ".join(f"{x['trial']} n={x['n']}" for x in cov["largest_trials_not_matched"][:2])
             + ") are open gaps, so no topic-level result is stated.", "",
             "| REACT trial | registration | state | route | sources (independent) | our row | REACT row | verdict | why not matched |",
             "|---|---|---|---|---|---|---|---|---|"]
    for t in r["trials"]:
        rr = t["react_row"]
        row = t["row"]
        ours = f"{row['deaths_t']}/{row['n_t']} vs {row['deaths_c']}/{row['n_c']} ({row['denominator_kind']})" if row else "-"
        src = "; ".join(f"{'+'.join(x['independent_sources'])}"
                        + (f" [{x['denominator_kind']}]" if x["denominator_kind"] == "SAFETY" else "") for x in t["readings"]) or "-"
        x = route[t["label"]]
        ov = x["our_value"]
        if x["route"] == "SECONDARY_SINGLE" and ov:
            ours = f"{ov['events_t']}/{ov['n_t']} vs {ov['events_c']}/{ov['n_c']} (meta row)"
        why = "" if x["route"] in tr.COUNTABLE else (x["secondary_single"].get("why") or x["basis"])[:220].replace("|", "/")
        lines.append(f"| {t['label']} | {t['registration'] or '-'} | {t['state']} | {x['route']} | {src} | {ours} | "
                     f"{rr['deaths_t']}/{rr['n_t']} vs {rr['deaths_c']}/{rr['n_c']} | {x['agreement_with_comparator_row']} | {why} |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
