"""Generate topic-specific offline replay instructions; --check refuses any byte drift."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read(path):
    return json.loads(path.read_text(encoding="utf-8"))


def topics(root=ROOT):
    return sorted(p for p in (root / "docs/reviews").iterdir() if (p / "manifest.json").is_file())


TARGET = "CPython 3.13 on Windows x86-64, Linux x86-64 (manylinux) or macOS arm64"


def dependency_binding(root=ROOT):
    """The dependency identity every guide and bundle names: the lock's digest and every acceptable wheel
    (PyPI-published sha256, size, URL). Wheel binaries are not vendored; pip --require-hashes verifies them."""
    return {"target": TARGET,
            "lock": {"served_path": "offline/requirements.lock",
                     "sha256": digest(root / "docs/offline/requirements.lock")},
            "wheels": [{k: w[k] for k in ("name", "version", "target", "file", "sha256", "bytes", "url") if k in w}
                       for w in read(root / "docs/offline/wheels.json")]}


def lock_failures(root=ROOT):
    """wheels.json and requirements.lock must name the same bytes, and a local mirror (docs/offline/wheels/ or
    scratch/wheels/), where present, must hold exactly those bytes."""
    failures = []
    lock = (root / "docs/offline/requirements.lock").read_text(encoding="utf-8")
    hashes = {}
    for line in lock.splitlines():
        if line.strip() and not line.startswith("#"):
            hashes[line.split()[0]] = {h.split(":", 1)[1] for h in line.split()[1:] if h.startswith("--hash=sha256:")}
    for w in read(root / "docs/offline/wheels.json"):
        pin = f"{w['name']}=={w['version']}" if "name" in w else None
        if pin is not None and w["sha256"] not in hashes.get(pin, set()):
            failures.append(f"wheel digest not in lock: {w['file']}")
        for mirror in (root / "docs/offline/wheels", root / "scratch/wheels"):
            path = mirror / w["file"]
            if path.is_file() and (digest(path) != w["sha256"] or path.stat().st_size != w["bytes"]):
                failures.append("wheel missing or changed: " + str(path))
    return failures


def render(directory, root=ROOT):
    slug = directory.name
    manifest = read(directory / "manifest.json")
    cert = read(directory / "CERTIFICATE.json")
    record_path = directory / "EXECUTION_RECORD.json"
    tree = read(record_path).get("tree", {}) if record_path.exists() else {}
    held = "\n".join(f"| `{x['ref']}` | `{x['sha256']}` |" for x in cert["held_documents"])
    blobs = cert["analysis_code_blobs"]
    lock = dependency_binding(root)["lock"]["sha256"]
    bundle_note = ("Inspect `BUNDLE.json.verification_rows` for this topic's admissions and `pooled_reference`\n"
                   "for its numerical reference; no other topic's estimate or control identifier is substituted."
                   if (directory / "BUNDLE.json").exists() else
                   "This topic has no independent-verifier BUNDLE.json; do not claim its row-verifier or anchor checks ran.\n"
                   "The corpus dependency and guide bindings are in `docs/offline/BUNDLE.json`.")
    return f"""<!-- GENERATED by scripts/generate_replay.py; never hand-maintain. -->
# Offline replay: {slug}

Run from the extracted repository root. Follow [the shared replay contract](../../offline/REPLAY.md)
for setup, exactness, provenance, controls and limits. No remote identity check is required.

```text
python -m venv scratch/replay-venv
python -m pip download --only-binary :all: --no-deps --require-hashes -r docs/offline/requirements.lock -d scratch/wheels
scratch/replay-venv/Scripts/python -m pip install --no-index --require-hashes --find-links scratch/wheels -r docs/offline/requirements.lock
scratch/replay-venv/Scripts/python scripts/generate_replay.py --check
scratch/replay-venv/Scripts/python scripts/replay_offline.py {slug} --report scratch/{slug}-replay.json
scratch/replay-venv/Scripts/python -m pytest tests/test_offline_replay.py -q --basetemp=scratch/pytest-replay
```

The `pip download` line is the ONE network step: it fetches only wheels whose SHA-256 the lock names (any other
bytes are refused), and it may be replaced by copying a verified mirror into `scratch/wheels/`. Everything after it
runs with networking and child processes denied. On Linux/macOS use `scratch/replay-venv/bin/python`.

| This topic's identity | Recorded value |
|---|---|
| review_sha256 (canonical review core) | `{manifest['review_sha256']}` |
| html_sha256 (served page bytes) | `{manifest['html_sha256']}` |
| release_sha256 (certificate) | `{cert['release_sha256']}` |
| build_utc (label, not clock) | `{manifest['build_utc']}` |
| protocol_sha | `{manifest['protocol_sha']}` |
| analysis code | {sum(v != 'NOT_PRESENT' for v in blobs.values())} pinned blobs; {sum(v == 'NOT_PRESENT' for v in blobs.values())} declared absences in CERTIFICATE.json.analysis_code_blobs |
| recorded generating commit | `{tree.get('generating_commit', 'UNRECORDED')}` |
| recorded tree state | `{tree.get('tree_state', 'UNRECORDED')}`; a commit alone does not restore dirty changes |
| dependency lock SHA-256 | `{lock}` |

## This topic's held documents

These are CERTIFICATE.json.held_documents, not an inferred source list. Availability and
licence/custody exceptions, where a topic bundle exists, remain in its artefacts and limits.

| Repository-relative document | SHA-256 |
|---|---|
{held}

Recorded judgments live under `cache/{slug}/`; their object digest is
`{cert['extraction_objects_sha256']}`. Acquisitions live under `docs/acquisitions/{slug}/`.
{bundle_note}
"""


def check(root=ROOT, write=False):
    failures = []
    binding = dependency_binding(root)
    failures = lock_failures(root)
    if failures:
        return failures
    corpus = {"dependencies": binding, "topics": []}
    for directory in topics(root):
        path = directory / "REPLAY.md"
        wanted = render(directory, root).encode("utf-8")
        if write:
            path.write_bytes(wanted)
        elif not path.is_file() or path.read_bytes() != wanted:
            failures.append("REPLAY.md stale or absent: " + directory.name)
        bundle_path = directory / "BUNDLE.json"
        corpus["topics"].append({"slug": directory.name,
                                 "guide": f"reviews/{directory.name}/REPLAY.md",
                                 "sha256": hashlib.sha256(wanted).hexdigest()})
        if not bundle_path.is_file():
            continue
        bundle = read(bundle_path)
        if write:
            # Update only this new replay contract; do not restamp historical build metadata.
            bundle["offline_replay"] = binding
            files = [f for f in bundle["review_files"] if f["file"] != "REPLAY.md"]
            files.append({"file": "REPLAY.md", "served_path": f"reviews/{directory.name}/REPLAY.md",
                          "served_url": files[0]["served_url"].rsplit("/", 1)[0] + "/REPLAY.md",
                          "sha256": hashlib.sha256(wanted).hexdigest(), "bytes": len(wanted),
                          "git_blob_sha1": hashlib.sha1(b"blob " + str(len(wanted)).encode() + b"\0" + wanted).hexdigest()})
            bundle["review_files"] = sorted(files, key=lambda f: f["file"])
            bundle_path.write_text(json.dumps(bundle, indent=1, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
        elif bundle.get("offline_replay") != binding:
            failures.append("bundle dependency binding stale: " + directory.name)
        elif next((f.get("sha256") for f in bundle["review_files"] if f["file"] == "REPLAY.md"), None) != hashlib.sha256(wanted).hexdigest():
            failures.append("bundle REPLAY binding stale: " + directory.name)
    corpus_path = root / "docs/offline/BUNDLE.json"
    expected = (json.dumps(corpus, indent=2) + "\n").encode("utf-8")
    if write:
        corpus_path.write_bytes(expected)
    elif not corpus_path.is_file() or corpus_path.read_bytes() != expected:
        failures.append("corpus replay bundle stale or absent")
    return failures


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    failures = check(write=not args.check)
    for failure in failures:
        print("REFUSED: " + failure)
    total = len(topics())
    print(f"{'CHECKED' if args.check else 'GENERATED'} {total} topic guides; {len(failures)} failures")
    return int(bool(failures))


if __name__ == "__main__":
    raise SystemExit(main())
