"""Incremental per-topic rebuilds from a recorded, digest-based dependency map.

  record [SLUG ...] [--now D]    rebuild each topic (default: all) while an audit hook records every repository file
                                 the build READS (open, git show HEAD:<path>) and every directory it LISTS; writes
                                 registry/build_deps/<slug>.json = {file: git blob sha, dir: listing sha256}
  plan                           which topics are stale: any recorded input whose identity changed (one batched
                                 `git hash-object` for every file of every topic), a missing map, or a changed
                                 interpreter/numeric stack; prints the first changed inputs as the reason
  run [--now D]                  rebuild (and re-record) exactly the stale topics; prints n rebuilt of N
  verify --sample K [--now D]    the equivalence proof: for K topics `plan` calls current, rebuild them anyway and
                                 require every output byte-identical to the committed bytes, except the two files an
                                 unchanged rebuild always rewrites (EXECUTION_RECORD.json: build provenance;
                                 registry/blind_map.json: last-topic-built side file). Restores the tree after.

A file the build WRITES is an output, never an input (otherwise every build would invalidate itself). The map is
evidence about one build of one tree; when in doubt (no map, unreadable input, new interpreter) the topic is
rebuilt -- staleness is never assumed away.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
DEPS = ROOT / "registry" / "build_deps"
VOLATILE = {"EXECUTION_RECORD.json"}            # rewritten by every build (provenance: time, cwd, commit, dirty paths)
SIDE_FILES = {"registry/blind_map.json"}        # last-topic-built side file, not a per-topic output
SKIP_PARTS = {".git", "__pycache__", "scratch", ".pytest_cache"}


def _rel(path) -> str | None:
    try:
        p = Path(os.fsdecode(path)).resolve()
    except (OSError, ValueError, TypeError):
        return None
    try:
        rel = p.relative_to(ROOT).as_posix()
    except ValueError:
        return None
    if not rel or any(part in SKIP_PARTS for part in rel.split("/")) or rel.startswith("registry/build_deps"):
        return None
    return rel


def _listing_sha(rel: str) -> str | None:
    d = ROOT / rel
    if not d.is_dir():
        return None
    names = sorted(e.name + ("/" if e.is_dir() else "") for e in os.scandir(d))
    return hashlib.sha256("\n".join(names).encode("utf-8")).hexdigest()


def environment() -> dict:
    import importlib.metadata as md
    env = {"python": sys.version.split()[0]}
    for dist in ("numpy", "scipy"):
        try:
            env[dist] = md.version(dist)
        except md.PackageNotFoundError:
            env[dist] = None
    return env


def _build_recorded(slug: str, now: str) -> int:
    """Child process: run build_topic.main for one slug under the audit hook, then write its dependency map."""
    reads, writes, dirs = set(), set(), set()
    paused = [False]

    def hook(event, args):
        if paused[0]:
            return
        if event == "open" and args and args[0] is not None and not isinstance(args[0], int):
            rel = _rel(args[0])
            if rel is None:
                return
            mode = args[1] if len(args) > 1 and isinstance(args[1], str) else "r"
            flags = args[2] if len(args) > 2 and isinstance(args[2], int) else 0
            if any(c in (mode or "") for c in "wax+") or flags & (os.O_WRONLY | os.O_RDWR | os.O_CREAT):
                writes.add(rel)
            else:
                reads.add(rel)
        elif event in ("os.listdir", "os.scandir") and args and args[0] is not None:
            rel = _rel(args[0] if not isinstance(args[0], int) else ".")
            if rel is not None:
                dirs.add(rel)
        elif event == "subprocess.Popen" and len(args) > 1 and isinstance(args[1], (list, tuple)):
            argv = [str(a) for a in args[1]]
            if "show" in argv:
                for a in argv:
                    if a.startswith("HEAD:"):
                        reads.add(a[5:])

    sys.addaudithook(hook)
    # Corpus-level steps are not this topic's dependencies: write_index reads EVERY page (so attributing its reads
    # would make any change anywhere invalidate every topic) and the execution record reads tree provenance. Their
    # writes are still outputs; the index is regenerated by whichever topic is rebuilt last, from all current pages.
    import harness.index as _index
    sys.path.insert(0, str(ROOT / "scripts"))
    import execution_record as _er  # build_topic imports it by this top-level name

    def _paused(fn):
        def wrapper(*a, **k):
            paused[0] = True
            try:
                return fn(*a, **k)
            finally:
                paused[0] = False
        return wrapper

    _index.write_index = _paused(_index.write_index)
    _er.write_execution_record = _paused(_er.write_execution_record)
    sys.argv = ["build_topic.py", slug, "--now", now]
    import runpy
    try:
        runpy.run_path(str(ROOT / "scripts" / "build_topic.py"), run_name="__main__")
    except SystemExit as exc:
        if exc.code not in (0, None):
            return int(exc.code) if isinstance(exc.code, int) else 1
    files = sorted(r for r in reads - writes if (ROOT / r).is_file())
    from harness import gitblob
    shas = gitblob.blob_shas(ROOT, files)
    record = {"slug": slug, "now": now, "environment": environment(),
              "files": {f: shas[f] for f in files},
              "dirs": {d: _listing_sha(d) for d in sorted(dirs) if (ROOT / d).is_dir()},
              "outputs": sorted(w for w in writes if w not in SIDE_FILES)}
    DEPS.mkdir(parents=True, exist_ok=True)
    (DEPS / f"{slug}.json").write_text(json.dumps(record, indent=1, sort_keys=True) + "\n", encoding="utf-8",
                                       newline="\n")
    return 0


def slugs() -> list[str]:
    return sorted(p.name for p in (ROOT / "docs" / "reviews").iterdir() if (p / "review.json").is_file())


def build(slug: str, now: str) -> bool:
    proc = subprocess.run([sys.executable, str(Path(__file__)), "_build", slug, "--now", now], cwd=ROOT,
                          capture_output=True, text=True, encoding="utf-8", errors="replace", stdin=subprocess.DEVNULL)
    if proc.returncode != 0:
        print(f"BUILD FAIL {slug}: {(proc.stderr or proc.stdout)[-400:]}")
        return False
    if (ROOT / "docs" / "reviews" / slug / "BUNDLE.json").is_file():
        # a bundled topic's manifest source block and BUNDLE.json are restamped AFTER the page build (the bundle
        # builder refuses until the replay guides are current): guides -> bundle -> guides, as a full chain does
        for step in (["scripts/generate_replay.py"], ["scripts/build_bundle.py", slug], ["scripts/generate_replay.py"]):
            post = subprocess.run([sys.executable, *step], cwd=ROOT, capture_output=True, text=True, encoding="utf-8",
                                  errors="replace", stdin=subprocess.DEVNULL)
            if post.returncode != 0:
                print(f"POST-STEP FAIL {slug} {step}: {(post.stdout + post.stderr)[-400:]}")
                return False
    return True


def plan() -> dict[str, list[str]]:
    """{slug: reasons} for every stale topic; current topics are absent. One batched blob call for all files."""
    from harness import gitblob
    maps, stale = {}, {}
    for s in slugs():
        p = DEPS / f"{s}.json"
        if not p.is_file():
            stale[s] = ["no dependency map recorded"]
            continue
        maps[s] = json.loads(p.read_text(encoding="utf-8"))
    every = sorted({f for m in maps.values() for f in m["files"]})
    current = gitblob.blob_shas(ROOT, every)
    env = environment()
    for s, m in maps.items():
        why = []
        if m.get("environment") != env:
            why.append(f"environment {m.get('environment')} -> {env}")
        why += [f"file {f}" for f, sha in m["files"].items() if current.get(f) != sha]
        why += [f"listing {d}" for d, sha in m["dirs"].items() if _listing_sha(d) != sha]
        if why:
            stale[s] = why
    return stale


def _snapshot(slug: str) -> dict[str, bytes]:
    m = json.loads((DEPS / f"{slug}.json").read_text(encoding="utf-8"))
    out = {}
    # EXECUTION_RECORD.json is written inside the paused provenance step, so the hook never sees it as an output;
    # it must still be restored, or a bundled topic's BUNDLE.json would bind a record that is no longer on disk.
    extra = [f"docs/reviews/{slug}/EXECUTION_RECORD.json", f"docs/reviews/{slug}/BUNDLE.json",
             f"docs/reviews/{slug}/REPLAY.md", "docs/offline/BUNDLE.json"]
    for rel in list(m["outputs"]) + [e for e in extra if (ROOT / e).is_file()]:
        p = ROOT / rel
        if p.is_file():
            out[rel] = p.read_bytes()
    return out


def _provenance_masked(rel: str, data: bytes | None) -> bytes | None:
    """For a bundled topic, BUNDLE.json and manifest.json bind the EXECUTION_RECORD's digest and time (provenance,
    declared non-exact in docs/offline/REPLAY.md). Mask exactly those fields -- and the review_files rows for
    EXECUTION_RECORD.json and manifest.json, whose bytes differ only by them -- before comparing. Everything else
    must still be byte-identical."""
    name = Path(rel).name
    if data is None or name not in ("BUNDLE.json", "manifest.json") or "/reviews/" not in rel:
        return data
    obj = json.loads(data.decode("utf-8"))
    src = obj.get("source") if isinstance(obj.get("source"), dict) else None
    if src and isinstance(src.get("execution_record"), dict):
        for k in ("sha256", "utc"):
            src["execution_record"].pop(k, None)
    if isinstance(obj.get("review_files"), list):
        obj["review_files"] = [f for f in obj["review_files"]
                               if f.get("file") not in ("EXECUTION_RECORD.json", "manifest.json")]
    return json.dumps(obj, sort_keys=True, ensure_ascii=False).encode("utf-8")


def verify(sample: int, now: str, only: list[str] | None = None) -> int:
    current = [s for s in slugs() if s not in plan()]
    picked = [s for s in only if s in current] if only else (current[:: max(1, len(current) // sample)][:sample] if current else [])
    side = {r: (ROOT / r).read_bytes() for r in SIDE_FILES if (ROOT / r).is_file()}
    equal = 0
    for s in picked:
        before = _snapshot(s)
        dep_before = (DEPS / f"{s}.json").read_bytes()
        ok = build(s, now)
        after = _snapshot(s)
        diffs = [r for r in sorted(set(before) | set(after))
                 if Path(r).name not in VOLATILE
                 and _provenance_masked(r, before.get(r)) != _provenance_masked(r, after.get(r))]
        masked = [r for r in sorted(set(before) & set(after)) if before[r] != after[r] and r not in diffs
                  and Path(r).name not in VOLATILE]
        same = ok and not diffs and set(before) == set(after)
        equal += same
        print(f"{'EQUAL    ' if same else 'DIFFERENT'} {s}" + ("" if same else f": {diffs[:5]}")
              + (f"  (execution-record provenance fields masked in {masked})" if same and masked else ""))
        for rel, data in before.items():           # restore committed bytes, including provenance
            (ROOT / rel).write_bytes(data)
        (DEPS / f"{s}.json").write_bytes(dep_before)
    for rel, data in side.items():
        (ROOT / rel).write_bytes(data)
    print(f"incremental == full rebuild: {equal} of {len(picked)} sampled current topics")
    return 0 if picked and equal == len(picked) else 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("_build"); b.add_argument("slug"); b.add_argument("--now", required=True)
    r = sub.add_parser("record"); r.add_argument("slugs", nargs="*"); r.add_argument("--now", default="2026-09-11")
    sub.add_parser("plan")
    u = sub.add_parser("run"); u.add_argument("--now", default="2026-09-11")
    v = sub.add_parser("verify"); v.add_argument("--sample", type=int, default=4); v.add_argument("--now", default="2026-09-11")
    v.add_argument("--slugs", nargs="*", default=None, help="verify these current topics instead of a sample")
    a = ap.parse_args(argv)
    if a.cmd == "_build":
        return _build_recorded(a.slug, a.now)
    if a.cmd == "record":
        todo = a.slugs or slugs()
        ok = sum(build(s, a.now) for s in todo)
        print(f"recorded {ok} of {len(todo)}")
        return 0 if ok == len(todo) else 1
    if a.cmd == "plan":
        st = plan()
        for s, why in sorted(st.items()):
            print(f"STALE {s}: {'; '.join(why[:4])}" + (f" (+{len(why) - 4} more)" if len(why) > 4 else ""))
        print(f"{len(st)} of {len(slugs())} topics stale")
        return 0
    if a.cmd == "run":
        st = plan()
        ok = sum(build(s, a.now) for s in sorted(st))
        print(f"rebuilt {ok} of {len(st)} stale ({len(slugs())} topics)")
        return 0 if ok == len(st) else 1
    return verify(a.sample, a.now, a.slugs)


if __name__ == "__main__":
    sys.exit(main())
