"""Generate every topic's parent-registration links from the regex proposer (harness/parent_registration.propose), and
measure the corpus (V1.0.1, statins-older-adults review). No link is hand-written: cache/<slug>/parent_registrations.json
holds only LINKED rows, each re-validated by harness/parent_registration.validate at build time.

  python scripts/parent_registrations.py [--write]
    -> cache/<slug>/parent_registrations.json (topics with a LINKED row; a stale file is removed)
    -> evidence/v101_integrated/parent_registration_sweep.json:
       N  held reports that name themselves an analysis of a named trial and carry no registration, by state;
       and, for the recovery panel, every missed report typed 'no_registry_link' (cache/<slug>/recall.json) --
       how many are registered through a parent the proposer links.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from harness import parent_registration as pr  # noqa: E402

SWEEP = ROOT / "evidence" / "v101_integrated" / "parent_registration_sweep.json"


def main(argv):
    write = "--write" in argv
    rows, recall = [], []
    for page in sorted((ROOT / "docs" / "reviews").iterdir()):
        slug = page.name
        rp = ROOT / "cache" / slug / "records.json"
        if not rp.exists():
            continue
        records = json.loads(rp.read_text(encoding="utf-8"))
        by_id = {str(r.get("id")): r for v in records.values() if isinstance(v, list) for r in v if isinstance(r, dict)}
        props = pr.propose(ROOT, slug, records)
        links = []
        for x in props:
            rows.append(dict(x, slug=slug))
            if x["state"] == "LINKED":
                link = {k: x[k] for k in ("pmid", "nct", "acronym", "paper_quote", "registry_quote")}
                link["generated_by"] = "harness/parent_registration.propose (regex SELF_ANALYSIS + one held registration)"
                pr.validate(ROOT, slug, link, by_id)
                links.append(link)
        out = ROOT / "cache" / slug / "parent_registrations.json"
        if write:
            if links:
                out.write_text(json.dumps({"schema": "parent-registrations-v1", "slug": slug,
                                           "_doc": "GENERATED by scripts/parent_registrations.py; never hand-edited.",
                                           "links": links}, indent=1, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
            elif out.exists():
                out.unlink()
        rc = ROOT / "cache" / slug / "recall.json"
        if rc.exists():
            r = json.loads(rc.read_text(encoding="utf-8"))
            linked = {x["pmid"]: x["nct"] for x in props if x["state"] == "LINKED"}
            for m, why in (r.get("missed_reasons") or {}).items():
                if why == "no_registry_link":
                    recall.append({"slug": slug, "pmid": str(m), "parent": linked.get(str(m)),
                                   "proposer_state": next((x["state"] for x in props if x["pmid"] == str(m)), "NOT_A_SELF_NAMED_ANALYSIS")})
    by = {}
    for x in rows:
        by[x["state"]] = by.get(x["state"], 0) + 1
    doc = {"schema": "parent-registration-sweep-v1",
           "N_self_named_analyses_without_registration": len(rows), "by_state": by,
           "recall_no_registry_link": {"N": len(recall), "n_registered_through_parent": sum(1 for x in recall if x["parent"]),
                                       "items": recall},
           "rows": [{k: x.get(k) for k in ("slug", "pmid", "acronym", "state", "nct", "phrase", "candidates",
                                            "held_reports_of_registration") if x.get(k) is not None} for x in rows]}
    if write:
        SWEEP.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    print("self-named analyses:", len(rows), by)
    print("recall no_registry_link: n registered through a parent =", doc["recall_no_registry_link"]["n_registered_through_parent"],
          "of N =", len(recall))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
