"""Record, route by route, whether each PENDING_SOURCE positive control's source can be held (V1.0.1, statins-older-adults
review). A control's "not held" is then a recorded result of real requests, not a sentence someone typed.

For every control in registry/positive_controls.json with state PENDING_SOURCE and a `pmid`:
  PMC_IDCONV     the PMC ID converter: is the article in PMC at all?
  EUROPE_PMC     Europe PMC core record: isOpenAccess / inEPMC / licence
  PUBLISHER_DOI  https://doi.org/<doi>: the landing page -- a bot-verification page is recorded as
                 BOT_CHECK_NOT_BYPASSED and is never retried around, solved or bypassed
Each request is logged (URL, UTC, HTTP status, bytes, sha256) with a typed route state:
  OPEN_FULL_TEXT | IN_PMC_NOT_OPEN | NOT_IN_PMC | NOT_OPEN_ACCESS | BOT_CHECK_NOT_BYPASSED | HTTP_<code> | FETCH_FAILED
-> registry/positive_control_acquisition.json (harness/positive_control.pending_problems reads it at build time)

  python scripts/positive_control_acquire.py [--write]
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from harness import positive_control as pc  # noqa: E402

TOOL = "tool=meta-harness&email=meta-harness@example.org"
BOT = re.compile(r"(?i)just a moment|cf-chl|cloudflare|captcha|verify you are human|are you a robot|access denied")


def _get(url):
    t0 = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "meta-harness (positive-control acquisition)"})
        with urllib.request.urlopen(req, timeout=60) as r:
            body, status = r.read(), r.status
    except urllib.error.HTTPError as exc:
        body, status = exc.read() or b"", exc.code
    except Exception as exc:  # noqa: BLE001 -- recorded as FETCH_FAILED, never read as "not held"
        body, status = b"", f"ERROR {type(exc).__name__}"
    time.sleep(0.5)
    return {"url": url, "utc": t0, "status": status, "bytes": len(body),
            "sha256": hashlib.sha256(body).hexdigest() if body else None}, body


def routes(control):
    pmid, doi = str(control.get("pmid") or ""), str(control.get("doi") or "")
    out = []
    req, body = _get(f"https://pmc.ncbi.nlm.nih.gov/tools/idconv/api/v1/articles/?ids={pmid}&format=json&{TOOL}")
    try:
        rec = (json.loads(body).get("records") or [{}])[0]
        state = "IN_PMC" if rec.get("pmcid") else "NOT_IN_PMC"
    except ValueError:
        state = "FETCH_FAILED"
    out.append(dict(req, route="PMC_IDCONV", state=state))
    req, body = _get(f"https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=EXT_ID:{pmid}%20AND%20SRC:MED"
                     f"&format=json&resultType=core")
    try:
        r = (json.loads(body)["resultList"]["result"] or [{}])[0]
        state = ("OPEN_FULL_TEXT" if r.get("isOpenAccess") == "Y" else
                 "IN_PMC_NOT_OPEN" if r.get("inPMC") == "Y" or r.get("inEPMC") == "Y" else "NOT_OPEN_ACCESS")
    except (ValueError, KeyError):
        state = "FETCH_FAILED"
    out.append(dict(req, route="EUROPE_PMC", state=state))
    if doi:
        req, body = _get(f"https://doi.org/{doi}")
        text = body[:200000].decode("utf-8", "replace")
        state = ("BOT_CHECK_NOT_BYPASSED" if BOT.search(text) else
                 f"HTTP_{req['status']}" if req["status"] != 200 else "LANDING_PAGE_READ")
        out.append(dict(req, route="PUBLISHER_DOI", state=state))
    return out


def main(argv):
    doc = {"schema": "positive-control-acquisition-v1",
           "_doc": "GENERATED by scripts/positive_control_acquire.py; each row is a real request and its typed result.",
           "controls": {}}
    for c in pc.load(ROOT):
        if c.get("state") != "PENDING_SOURCE" or not c.get("pmid"):
            continue
        doc["controls"][c["id"]] = {"pmid": c["pmid"], "doi": c.get("doi"), "attempts": routes(c)}
        print(c["id"], [(a["route"], a["state"]) for a in doc["controls"][c["id"]]["attempts"]], flush=True)
    if "--write" in argv:
        (ROOT / pc.ACQUISITION).write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
