"""Owner-facing list of served analysis-set labels that the held source does not support, derived (never hand-edited)
from evidence/sweeps/entry_age_and_analysis_set.json and the adjudications. For each row whose served label is
'intention-to-treat' and the sweep reads CONTRADICTED (a bound span names another set) or UNSUPPORTED (no span
states a set), print the served row and the span. Labels only: no served number moves, nothing lands unsigned.
P53 rows are Evidence lane two's scope since 2026-09-24; they are listed so the owner sees one complete list."""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
import verify_records as V
ROOT = V.ROOT


def main():
    sw = json.load(open(os.path.join(ROOT, "evidence/sweeps/entry_age_and_analysis_set.json"), encoding="utf-8"))
    rows = sw["rows"]
    out = {"CONTRADICTED": [], "UNSUPPORTED": []}
    for k in sorted(rows):
        st = rows[k].get("served_itt_label")
        if st not in out:
            continue
        a = json.load(open(os.path.join(ROOT, f"evidence/adjudication/{k}.json"), encoding="utf-8"))
        pk = json.load(open(os.path.join(ROOT, f"evidence/packets/{k}.json"), encoding="utf-8"))
        ev = (a.get("evidence") or {}).get("analysis_set") or {}
        te = (a.get("typed_estimand") or {}).get("analysis_set")   # a dict in drafted rulings, one string in early ones
        why = te.get("absent_reason") if isinstance(te, dict) else te
        line = (f"- **{k}** {pk['slug']} / {pk['served_outcome']['name']} / {pk['trial']}"
                + (" *(P53: Evidence lane two's scope)*" if k.startswith("P53") else "") + "\n")
        if ev.get("span"):
            s = ev["span"]   # a registry line names the set at its END ('... | POPULATION: TS'): never cut the tail
            line += f"  - bound span ({ev['ref']}): \"{s if len(s) <= 320 else s[:140] + ' [...] ' + s[-170:]}\"\n"
        elif why:
            line += f"  - no span states a set: {str(why)[:300]}\n"
        out[st].append(line)
    want = sw["summary"]["served_itt_label"]
    for st in out:   # the list must account for exactly the rows the sweep counted, or it is not the list
        if len(out[st]) != want[st]:
            sys.exit(f"REFUSED: listed {len(out[st])} {st} rows, the sweep's summary counts {want[st]}")
    n = len(out["CONTRADICTED"]) + len(out["UNSUPPORTED"])
    txt = ["# Served analysis-set label corrections (derived; do not hand-edit)\n",
           f"Generated by evidence/scripts/label_corrections.py from the analysis-set sweep. {n} served rows labelled "
           "'intention-to-treat' whose held source does not support the label. Labels only: no served number moves; "
           "each correction changes served text, so it is QUEUED for the owner, not landed.\n",
           f"\n## Contradicted: a bound span names another set ({len(out['CONTRADICTED'])})\n", *out["CONTRADICTED"],
           f"\n## Unsupported: no held span states the set ({len(out['UNSUPPORTED'])})\n", *out["UNSUPPORTED"]]
    open(os.path.join(ROOT, "evidence/LABEL_CORRECTIONS.md"), "w", encoding="utf-8", newline="\n").write("".join(txt))
    print(f"label corrections: contradicted {len(out['CONTRADICTED'])}, unsupported {len(out['UNSUPPORTED'])}")


if __name__ == "__main__":
    main()
