"""Tally the evidence records. Every count is printed as n of N with N named; rows with no extraction yet,
rows whose extraction fails verification and rows that verify are three different kinds and are never merged."""
import json, os, sys, collections
sys.path.insert(0, os.path.dirname(__file__))
import textrep
ROOT = textrep.ROOT
FIELDS = ("population", "endpoint", "estimate", "ci", "analysis_set", "treatment_strategy", "follow_up")


def main():
    wl = json.load(open(os.path.join(ROOT, "evidence/worklist.json"), encoding="utf-8"))["rows"]
    ver = json.load(open(os.path.join(ROOT, "evidence/extractions/verification.json"), encoding="utf-8"))
    adj_dir = os.path.join(ROOT, "evidence/adjudication")
    adj = {f[:-5]: json.load(open(os.path.join(adj_dir, f), encoding="utf-8"))
           for f in (os.listdir(adj_dir) if os.path.isdir(adj_dir) else []) if f.endswith(".json")}
    out, lines = {}, []
    for pop, N in (("P53", 53), ("U23", 23)):
        rows = [w for w in wl if w["kind"] == pop]
        assert len(rows) == N, (pop, len(rows))
        c = collections.Counter(); fc = collections.Counter(); ep = collections.Counter(); sa = collections.Counter()
        per = []
        for w in rows:
            k = w["key"]; v = ver.get(k)
            raw = os.path.join(ROOT, f"evidence/extractions/raw/{k}.json")
            rec = json.load(open(raw, encoding="utf-8")) if os.path.exists(raw) else None
            a = adj.get(k)
            if v is None:
                kind = "NOT_YET_EXTRACTED"
            elif v["errors"]:
                kind = "EXTRACTION_FAILS_VERIFICATION"
            else:
                kind = "VERIFIED_" + (v["verdict"] or "NONE")
            c[kind] += 1
            if kind == "VERIFIED_BOUND":
                for f in FIELDS:
                    fc[f] += f in v["spans"]
                c["served_" + ((v.get("served_compare") or {}).get("state") or "NONE")] += 1
            if kind == "VERIFIED_SET_ASIDE":
                sa[rec.get("set_aside_reason") or "UNSTATED"] += 1
            if rec and not (v or {}).get("errors"):
                ep[(rec.get("entry_population_matches_question") or {}).get("value") or "NONE"] += 1
            if a:
                c["adjudicated"] += 1
                c["adjudication_" + a.get("ruling", "NONE")] += 1
            per.append({"key": k, "slug": w["slug"], "trial": w["trial"], "kind": kind,
                        "served": ((v or {}).get("served_compare") or {}).get("state"),
                        "entry_population": ((rec or {}).get("entry_population_matches_question") or {}).get("value"),
                        "adjudication": (a or {}).get("ruling")})
        out[pop] = {"N": N, "counts": dict(c), "fields_bound_among_verified_bound": dict(fc),
                    "entry_population_ruling_extractor": dict(ep), "set_aside_reasons": dict(sa), "rows": per}
        nb = c["VERIFIED_BOUND"]
        lines.append(f"## {pop}: N = {N} ({'pooled primary rows inadmissible on P5 at 38c04411' if pop == 'P53' else 'served rows lane UA found with no locatable source'})")
        for kind in ("VERIFIED_BOUND", "VERIFIED_SET_ASIDE", "EXTRACTION_FAILS_VERIFICATION", "NOT_YET_EXTRACTED"):
            lines.append(f"- {kind}: {c[kind]} of {N}")
        lines.append(f"- among the {nb} verified BOUND: served MATCH {c['served_MATCH']}, DIFFERS {c['served_DIFFERS']}, "
                     f"NOT_COMPARABLE {c['served_NOT_COMPARABLE']} (each of {nb})")
        lines.append("- fields bound (of " + str(nb) + " verified BOUND): " + ", ".join(f"{f} {fc[f]}" for f in FIELDS))
        lines.append("- extractor's entry-population reading (not a ruling): " + ", ".join(f"{k} {v}" for k, v in sorted(ep.items())))
        lines.append(f"- adjudicated by the lane: {c['adjudicated']} of {N}: " + ", ".join(f"{k[13:]} {v}" for k, v in sorted(c.items()) if k.startswith("adjudication_")))
        lines.append("")
    json.dump(out, open(os.path.join(ROOT, "evidence/ledger.json"), "w", encoding="utf-8"), indent=1)
    open(os.path.join(ROOT, "evidence/LEDGER.md"), "w", encoding="utf-8").write("# Evidence ledger (generated by evidence/scripts/ledger.py)\n\n" + "\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
